//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jackson.designer;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for CommonAttributeContentItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommonAttributeContentItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Metadata" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="Use" type="{http://v8.1c.ru/8.3/xcf/enums}CommonAttributeUse"/&gt;
 *         &lt;element name="ConditionalSeparation" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType("CommonAttributeContentItem", namespace = "http://v8.1c.ru/8.3/xcf/readable", propOrder = {
    "metadata",
    "use",
    "conditionalSeparation"
})
public class CommonAttributeContentItem {

    @JsonProperty("Metadata")
    protected String metadata;
    @JsonProperty("Use")
    @XmlSchemaType("string")
    protected CommonAttributeUse use;
    @JsonProperty("ConditionalSeparation")
    protected String conditionalSeparation;

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadata(String value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the use property.
     * 
     * @return
     *     possible object is
     *     {@link CommonAttributeUse }
     *     
     */
    public CommonAttributeUse getUse() {
        return use;
    }

    /**
     * Sets the value of the use property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonAttributeUse }
     *     
     */
    public void setUse(CommonAttributeUse value) {
        this.use = value;
    }

    /**
     * Gets the value of the conditionalSeparation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionalSeparation() {
        return conditionalSeparation;
    }

    /**
     * Sets the value of the conditionalSeparation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionalSeparation(String value) {
        this.conditionalSeparation = value;
    }

}
