//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jackson.designer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.JsonProperty;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeographicalSchemeLineType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GeographicalSchemeLineType"&gt;
 *   &lt;restriction base="{http://v8.1c.ru/8.1/data/ui}LineType"&gt;
 *     &lt;enumeration value="None"/&gt;
 *     &lt;enumeration value="Solid"/&gt;
 *     &lt;enumeration value="Dotted"/&gt;
 *     &lt;enumeration value="Dashed"/&gt;
 *     &lt;enumeration value="DashDotted"/&gt;
 *     &lt;enumeration value="DashDottedDotted"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType("GeographicalSchemeLineType", namespace = "http://v8.1c.ru/8.1/data/ui")
@XmlEnum
public enum GeographicalSchemeLineType {

    @JsonProperty("None")
    NONE("None"),
    @JsonProperty("Solid")
    SOLID("Solid"),
    @JsonProperty("Dotted")
    DOTTED("Dotted"),
    @JsonProperty("Dashed")
    DASHED("Dashed"),
    @JsonProperty("DashDotted")
    DASH_DOTTED("DashDotted"),
    @JsonProperty("DashDottedDotted")
    DASH_DOTTED_DOTTED("DashDottedDotted");
    private final String value;

    GeographicalSchemeLineType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GeographicalSchemeLineType fromValue(String v) {
        for (GeographicalSchemeLineType c: GeographicalSchemeLineType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
