//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jackson.designer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.JsonProperty;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HandlerInfoByID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HandlerInfoByID"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://v8.1c.ru/8.1/data/core}CompositeID"/&gt;
 *         &lt;element name="handleInfo" type="{http://v8.1c.ru/8.2/managed-application/cmi}HandlerInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType("HandlerInfoByID", namespace = "http://v8.1c.ru/8.2/managed-application/cmi", propOrder = {
    "id",
    "handleInfo"
})
public class HandlerInfoByID {

    @JsonProperty(required = true)
    protected String id;
    protected HandlerInfo handleInfo;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the handleInfo property.
     * 
     * @return
     *     possible object is
     *     {@link HandlerInfo }
     *     
     */
    public HandlerInfo getHandleInfo() {
        return handleInfo;
    }

    /**
     * Sets the value of the handleInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlerInfo }
     *     
     */
    public void setHandleInfo(HandlerInfo value) {
        this.handleInfo = value;
    }

}
