//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jackson.designer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.JsonProperty;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ManagedFormFieldType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ManagedFormFieldType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Default"/&gt;
 *     &lt;enumeration value="LabelField"/&gt;
 *     &lt;enumeration value="InputField"/&gt;
 *     &lt;enumeration value="CheckBoxField"/&gt;
 *     &lt;enumeration value="PictureField"/&gt;
 *     &lt;enumeration value="RadioButtonField"/&gt;
 *     &lt;enumeration value="SpreadsheetDocumentField"/&gt;
 *     &lt;enumeration value="TextDocumentField"/&gt;
 *     &lt;enumeration value="FormattedDocumentField"/&gt;
 *     &lt;enumeration value="PlannerField"/&gt;
 *     &lt;enumeration value="CalendarField"/&gt;
 *     &lt;enumeration value="PeriodField"/&gt;
 *     &lt;enumeration value="ProgressBarField"/&gt;
 *     &lt;enumeration value="TrackBarField"/&gt;
 *     &lt;enumeration value="ChartField"/&gt;
 *     &lt;enumeration value="GanttChartField"/&gt;
 *     &lt;enumeration value="DendrogramField"/&gt;
 *     &lt;enumeration value="GraphicalSchemaField"/&gt;
 *     &lt;enumeration value="HTMLDocumentField"/&gt;
 *     &lt;enumeration value="GeographicalSchemaField"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType("ManagedFormFieldType", namespace = "http://v8.1c.ru/8.2/managed-application/logform")
@XmlEnum
public enum ManagedFormFieldType {

    @JsonProperty("Default")
    DEFAULT("Default"),
    @JsonProperty("LabelField")
    LABEL_FIELD("LabelField"),
    @JsonProperty("InputField")
    INPUT_FIELD("InputField"),
    @JsonProperty("CheckBoxField")
    CHECK_BOX_FIELD("CheckBoxField"),
    @JsonProperty("PictureField")
    PICTURE_FIELD("PictureField"),
    @JsonProperty("RadioButtonField")
    RADIO_BUTTON_FIELD("RadioButtonField"),
    @JsonProperty("SpreadsheetDocumentField")
    SPREADSHEET_DOCUMENT_FIELD("SpreadsheetDocumentField"),
    @JsonProperty("TextDocumentField")
    TEXT_DOCUMENT_FIELD("TextDocumentField"),
    @JsonProperty("FormattedDocumentField")
    FORMATTED_DOCUMENT_FIELD("FormattedDocumentField"),
    @JsonProperty("PlannerField")
    PLANNER_FIELD("PlannerField"),
    @JsonProperty("CalendarField")
    CALENDAR_FIELD("CalendarField"),
    @JsonProperty("PeriodField")
    PERIOD_FIELD("PeriodField"),
    @JsonProperty("ProgressBarField")
    PROGRESS_BAR_FIELD("ProgressBarField"),
    @JsonProperty("TrackBarField")
    TRACK_BAR_FIELD("TrackBarField"),
    @JsonProperty("ChartField")
    CHART_FIELD("ChartField"),
    @JsonProperty("GanttChartField")
    GANTT_CHART_FIELD("GanttChartField"),
    @JsonProperty("DendrogramField")
    DENDROGRAM_FIELD("DendrogramField"),
    @JsonProperty("GraphicalSchemaField")
    GRAPHICAL_SCHEMA_FIELD("GraphicalSchemaField"),
    @JsonProperty("HTMLDocumentField")
    HTML_DOCUMENT_FIELD("HTMLDocumentField"),
    @JsonProperty("GeographicalSchemaField")
    GEOGRAPHICAL_SCHEMA_FIELD("GeographicalSchemaField");
    private final String value;

    ManagedFormFieldType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ManagedFormFieldType fromValue(String v) {
        for (ManagedFormFieldType c: ManagedFormFieldType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
