//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jackson.designer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.JsonProperty;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NamedItemType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NamedItemType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Cells"/&gt;
 *     &lt;enumeration value="Drawing"/&gt;
 *     &lt;enumeration value="EmbeddedTable"/&gt;
 *     &lt;enumeration value="DataSource"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType("NamedItemType", namespace = "http://v8.1c.ru/8.2/data/spreadsheet")
@XmlEnum
public enum NamedItemType {

    @JsonProperty("Cells")
    CELLS("Cells"),
    @JsonProperty("Drawing")
    DRAWING("Drawing"),
    @JsonProperty("EmbeddedTable")
    EMBEDDED_TABLE("EmbeddedTable"),
    @JsonProperty("DataSource")
    DATA_SOURCE("DataSource");
    private final String value;

    NamedItemType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NamedItemType fromValue(String v) {
        for (NamedItemType c: NamedItemType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
