//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jackson.designer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.JsonProperty;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PivotTableLinesShowType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PivotTableLinesShowType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Auto"/&gt;
 *     &lt;enumeration value="Always"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType("PivotTableLinesShowType", namespace = "http://v8.1c.ru/8.2/data/spreadsheet")
@XmlEnum
public enum PivotTableLinesShowType {

    @JsonProperty("Auto")
    AUTO("Auto"),
    @JsonProperty("Always")
    ALWAYS("Always");
    private final String value;

    PivotTableLinesShowType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PivotTableLinesShowType fromValue(String v) {
        for (PivotTableLinesShowType c: PivotTableLinesShowType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
