//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package org.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ChoiceParameter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChoiceParameter"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mode" type="{http://v8.1c.ru/8.1/data/enterprise}LinkedValueChangeMode"/&gt;
 *         &lt;element name="pathItem" type="{http://v8.1c.ru/8.1/data/core}CompositeID" maxOccurs="unbounded"/&gt;
 *         &lt;element name="webDataPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChoiceParameter", namespace = "http://v8.1c.ru/8.2/managed-application/core", propOrder = {
    "name",
    "mode",
    "pathItem",
    "webDataPath",
    "strPath"
})
public class ChoiceParameter {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected LinkedValueChangeMode mode;
    @XmlElement(required = true)
    protected List<String> pathItem;
    protected String webDataPath;
    protected String strPath;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link LinkedValueChangeMode }
     *     
     */
    public LinkedValueChangeMode getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkedValueChangeMode }
     *     
     */
    public void setMode(LinkedValueChangeMode value) {
        this.mode = value;
    }

    /**
     * Gets the value of the pathItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pathItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPathItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPathItem() {
        if (pathItem == null) {
            pathItem = new ArrayList<String>();
        }
        return this.pathItem;
    }

    /**
     * Gets the value of the webDataPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebDataPath() {
        return webDataPath;
    }

    /**
     * Sets the value of the webDataPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebDataPath(String value) {
        this.webDataPath = value;
    }

    /**
     * Gets the value of the strPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrPath() {
        return strPath;
    }

    /**
     * Sets the value of the strPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrPath(String value) {
        this.strPath = value;
    }

}
