//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package org.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ConfigurationProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigurationProperties"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Synonym" type="{http://v8.1c.ru/8.1/data/core}LocalStringType"/&gt;
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ObjectBelonging" type="{http://v8.1c.ru/8.3/xcf/enums}ObjectBelonging"/&gt;
 *         &lt;element name="ConfigurationExtensionPurpose" type="{http://v8.1c.ru/8.3/xcf/enums}ConfigurationExtensionPurpose"/&gt;
 *         &lt;element name="NamePrefix" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ConfigurationExtensionCompatibilityMode" type="{http://v8.1c.ru/8.3/xcf/enums}CompatibilityMode"/&gt;
 *         &lt;element name="DefaultRunMode" type="{http://v8.1c.ru/8.2/managed-application/core}ClientRunMode"/&gt;
 *         &lt;element name="UsePurposes" type="{http://v8.1c.ru/8.1/data/core}FixedArray"/&gt;
 *         &lt;element name="ScriptVariant" type="{http://v8.1c.ru/8.3/xcf/enums}ScriptVariant"/&gt;
 *         &lt;element name="DefaultRoles" type="{http://v8.1c.ru/8.3/xcf/readable}MDListType"/&gt;
 *         &lt;element name="Vendor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UpdateCatalogAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ParentConfigurations" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="ManagedApplicationModule" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="SessionModule" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="ExternalConnectionModule" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="OrdinaryApplicationModule" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty" minOccurs="0"/&gt;
 *         &lt;element name="ApplicationModule" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty" minOccurs="0"/&gt;
 *         &lt;element name="IncludeHelpInContents" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Help" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="UseManagedFormInOrdinaryApplication" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="UseOrdinaryFormInManagedApplication" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AdditionalFullTextSearchDictionaries" type="{http://v8.1c.ru/8.3/xcf/readable}MDListType"/&gt;
 *         &lt;element name="CommonSettingsStorage" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="ReportsUserSettingsStorage" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="ReportsVariantsStorage" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="FormDataSettingsStorage" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="DynamicListsUserSettingsStorage" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="Content" type="{http://v8.1c.ru/8.3/xcf/readable}MDListType"/&gt;
 *         &lt;element name="DefaultReportForm" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="DefaultReportVariantForm" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="DefaultReportSettingsForm" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="DefaultDynamicListSettingsForm" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="DefaultSearchForm" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="RequiredMobileApplicationPermissions" type="{http://v8.1c.ru/8.1/data/core}FixedMap"/&gt;
 *         &lt;element name="CommandInterface" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="HomePageWorkArea" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty" minOccurs="0"/&gt;
 *         &lt;element name="StartPageWorkingArea" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty" minOccurs="0"/&gt;
 *         &lt;element name="MainSectionCommandInterface" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="MainSectionPicture" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="ClientApplicationInterface" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="MainClientApplicationWindowMode" type="{http://v8.1c.ru/8.1/data/core}MainClientApplicationWindowMode"/&gt;
 *         &lt;element name="DefaultInterface" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="DefaultStyle" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="DefaultLanguage" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="BriefInformation" type="{http://v8.1c.ru/8.1/data/core}LocalStringType"/&gt;
 *         &lt;element name="DetailedInformation" type="{http://v8.1c.ru/8.1/data/core}LocalStringType"/&gt;
 *         &lt;element name="Logo" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="Splash" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="Copyright" type="{http://v8.1c.ru/8.1/data/core}LocalStringType"/&gt;
 *         &lt;element name="VendorInformationAddress" type="{http://v8.1c.ru/8.1/data/core}LocalStringType"/&gt;
 *         &lt;element name="ConfigurationInformationAddress" type="{http://v8.1c.ru/8.1/data/core}LocalStringType"/&gt;
 *         &lt;element name="DataLockControlMode" type="{http://v8.1c.ru/8.3/xcf/enums}DefaultDataLockControlMode"/&gt;
 *         &lt;element name="ObjectAutonumerationMode" type="{http://v8.1c.ru/8.3/xcf/enums}ObjectAutonumerationMode"/&gt;
 *         &lt;element name="ModalityUseMode" type="{http://v8.1c.ru/8.3/xcf/enums}ModalityUseMode"/&gt;
 *         &lt;element name="SynchronousPlatformExtensionAndAddInCallUseMode" type="{http://v8.1c.ru/8.3/xcf/enums}SynchronousPlatformExtensionAndAddInCallUseMode" minOccurs="0"/&gt;
 *         &lt;element name="SynchronousExtensionAndAddInCallUseMode" type="{http://v8.1c.ru/8.3/xcf/enums}SynchronousPlatformExtensionAndAddInCallUseMode" minOccurs="0"/&gt;
 *         &lt;element name="InterfaceCompatibilityMode" type="{http://v8.1c.ru/8.3/xcf/enums}InterfaceCompatibilityMode"/&gt;
 *         &lt;element name="CompatibilityMode" type="{http://v8.1c.ru/8.3/xcf/enums}CompatibilityMode"/&gt;
 *         &lt;element name="DefaultConstantsForm" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef" minOccurs="0"/&gt;
 *         &lt;element name="DefaultConstantForm" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigurationProperties", propOrder = {
    "name",
    "synonym",
    "comment",
    "objectBelonging",
    "configurationExtensionPurpose",
    "namePrefix",
    "configurationExtensionCompatibilityMode",
    "defaultRunMode",
    "usePurposes",
    "scriptVariant",
    "defaultRoles",
    "vendor",
    "version",
    "updateCatalogAddress",
    "parentConfigurations",
    "managedApplicationModule",
    "sessionModule",
    "externalConnectionModule",
    "ordinaryApplicationModule",
    "applicationModule",
    "includeHelpInContents",
    "help",
    "useManagedFormInOrdinaryApplication",
    "useOrdinaryFormInManagedApplication",
    "additionalFullTextSearchDictionaries",
    "commonSettingsStorage",
    "reportsUserSettingsStorage",
    "reportsVariantsStorage",
    "formDataSettingsStorage",
    "dynamicListsUserSettingsStorage",
    "content",
    "defaultReportForm",
    "defaultReportVariantForm",
    "defaultReportSettingsForm",
    "defaultDynamicListSettingsForm",
    "defaultSearchForm",
    "requiredMobileApplicationPermissions",
    "commandInterface",
    "homePageWorkArea",
    "startPageWorkingArea",
    "mainSectionCommandInterface",
    "mainSectionPicture",
    "clientApplicationInterface",
    "mainClientApplicationWindowMode",
    "defaultInterface",
    "defaultStyle",
    "defaultLanguage",
    "briefInformation",
    "detailedInformation",
    "logo",
    "splash",
    "copyright",
    "vendorInformationAddress",
    "configurationInformationAddress",
    "dataLockControlMode",
    "objectAutonumerationMode",
    "modalityUseMode",
    "synchronousPlatformExtensionAndAddInCallUseMode",
    "synchronousExtensionAndAddInCallUseMode",
    "interfaceCompatibilityMode",
    "compatibilityMode",
    "defaultConstantsForm",
    "defaultConstantForm"
})
public class ConfigurationProperties {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Synonym")
    protected LocalStringType synonym;
    @XmlElement(name = "Comment")
    protected String comment;
    @XmlElement(name = "ObjectBelonging")
    @XmlSchemaType(name = "string")
    protected ObjectBelonging objectBelonging;
    @XmlElement(name = "ConfigurationExtensionPurpose")
    @XmlSchemaType(name = "string")
    protected ConfigurationExtensionPurpose configurationExtensionPurpose;
    @XmlElement(name = "NamePrefix")
    protected String namePrefix;
    @XmlElement(name = "ConfigurationExtensionCompatibilityMode")
    @XmlSchemaType(name = "string")
    protected CompatibilityMode configurationExtensionCompatibilityMode;
    @XmlElement(name = "DefaultRunMode")
    @XmlSchemaType(name = "string")
    protected ClientRunMode defaultRunMode;
    @XmlElement(name = "UsePurposes")
    protected FixedArray usePurposes;
    @XmlElement(name = "ScriptVariant")
    @XmlSchemaType(name = "string")
    protected ScriptVariant scriptVariant;
    @XmlElement(name = "DefaultRoles")
    protected MDListType defaultRoles;
    @XmlElement(name = "Vendor")
    protected String vendor;
    @XmlElement(name = "Version")
    protected String version;
    @XmlElement(name = "UpdateCatalogAddress")
    protected String updateCatalogAddress;
    @XmlElement(name = "ParentConfigurations")
    protected String parentConfigurations;
    @XmlElement(name = "ManagedApplicationModule")
    protected String managedApplicationModule;
    @XmlElement(name = "SessionModule")
    protected String sessionModule;
    @XmlElement(name = "ExternalConnectionModule")
    protected String externalConnectionModule;
    @XmlElement(name = "OrdinaryApplicationModule")
    protected String ordinaryApplicationModule;
    @XmlElement(name = "ApplicationModule")
    protected String applicationModule;
    @XmlElement(name = "IncludeHelpInContents")
    protected Boolean includeHelpInContents;
    @XmlElement(name = "Help")
    protected String help;
    @XmlElement(name = "UseManagedFormInOrdinaryApplication")
    protected Boolean useManagedFormInOrdinaryApplication;
    @XmlElement(name = "UseOrdinaryFormInManagedApplication")
    protected Boolean useOrdinaryFormInManagedApplication;
    @XmlElement(name = "AdditionalFullTextSearchDictionaries")
    protected MDListType additionalFullTextSearchDictionaries;
    @XmlElement(name = "CommonSettingsStorage")
    protected String commonSettingsStorage;
    @XmlElement(name = "ReportsUserSettingsStorage")
    protected String reportsUserSettingsStorage;
    @XmlElement(name = "ReportsVariantsStorage")
    protected String reportsVariantsStorage;
    @XmlElement(name = "FormDataSettingsStorage")
    protected String formDataSettingsStorage;
    @XmlElement(name = "DynamicListsUserSettingsStorage")
    protected String dynamicListsUserSettingsStorage;
    @XmlElement(name = "Content")
    protected MDListType content;
    @XmlElement(name = "DefaultReportForm")
    protected String defaultReportForm;
    @XmlElement(name = "DefaultReportVariantForm")
    protected String defaultReportVariantForm;
    @XmlElement(name = "DefaultReportSettingsForm")
    protected String defaultReportSettingsForm;
    @XmlElement(name = "DefaultDynamicListSettingsForm")
    protected String defaultDynamicListSettingsForm;
    @XmlElement(name = "DefaultSearchForm")
    protected String defaultSearchForm;
    @XmlElement(name = "RequiredMobileApplicationPermissions")
    protected FixedMap requiredMobileApplicationPermissions;
    @XmlElement(name = "CommandInterface")
    protected String commandInterface;
    @XmlElement(name = "HomePageWorkArea")
    protected String homePageWorkArea;
    @XmlElement(name = "StartPageWorkingArea")
    protected String startPageWorkingArea;
    @XmlElement(name = "MainSectionCommandInterface")
    protected String mainSectionCommandInterface;
    @XmlElement(name = "MainSectionPicture")
    protected String mainSectionPicture;
    @XmlElement(name = "ClientApplicationInterface")
    protected String clientApplicationInterface;
    @XmlElement(name = "MainClientApplicationWindowMode")
    @XmlSchemaType(name = "string")
    protected MainClientApplicationWindowMode mainClientApplicationWindowMode;
    @XmlElement(name = "DefaultInterface")
    protected String defaultInterface;
    @XmlElement(name = "DefaultStyle")
    protected String defaultStyle;
    @XmlElement(name = "DefaultLanguage")
    protected String defaultLanguage;
    @XmlElement(name = "BriefInformation")
    protected LocalStringType briefInformation;
    @XmlElement(name = "DetailedInformation")
    protected LocalStringType detailedInformation;
    @XmlElement(name = "Logo")
    protected String logo;
    @XmlElement(name = "Splash")
    protected String splash;
    @XmlElement(name = "Copyright")
    protected LocalStringType copyright;
    @XmlElement(name = "VendorInformationAddress")
    protected LocalStringType vendorInformationAddress;
    @XmlElement(name = "ConfigurationInformationAddress")
    protected LocalStringType configurationInformationAddress;
    @XmlElement(name = "DataLockControlMode")
    @XmlSchemaType(name = "string")
    protected DefaultDataLockControlMode dataLockControlMode;
    @XmlElement(name = "ObjectAutonumerationMode")
    @XmlSchemaType(name = "string")
    protected ObjectAutonumerationMode objectAutonumerationMode;
    @XmlElement(name = "ModalityUseMode")
    @XmlSchemaType(name = "string")
    protected ModalityUseMode modalityUseMode;
    @XmlElement(name = "SynchronousPlatformExtensionAndAddInCallUseMode")
    @XmlSchemaType(name = "string")
    protected SynchronousPlatformExtensionAndAddInCallUseMode synchronousPlatformExtensionAndAddInCallUseMode;
    @XmlElement(name = "SynchronousExtensionAndAddInCallUseMode")
    @XmlSchemaType(name = "string")
    protected SynchronousPlatformExtensionAndAddInCallUseMode synchronousExtensionAndAddInCallUseMode;
    @XmlElement(name = "InterfaceCompatibilityMode")
    @XmlSchemaType(name = "string")
    protected InterfaceCompatibilityMode interfaceCompatibilityMode;
    @XmlElement(name = "CompatibilityMode")
    @XmlSchemaType(name = "string")
    protected CompatibilityMode compatibilityMode;
    @XmlElement(name = "DefaultConstantsForm")
    protected String defaultConstantsForm;
    @XmlElement(name = "DefaultConstantForm")
    protected String defaultConstantForm;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the synonym property.
     * 
     * @return
     *     possible object is
     *     {@link LocalStringType }
     *     
     */
    public LocalStringType getSynonym() {
        return synonym;
    }

    /**
     * Sets the value of the synonym property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalStringType }
     *     
     */
    public void setSynonym(LocalStringType value) {
        this.synonym = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the objectBelonging property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectBelonging }
     *     
     */
    public ObjectBelonging getObjectBelonging() {
        return objectBelonging;
    }

    /**
     * Sets the value of the objectBelonging property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectBelonging }
     *     
     */
    public void setObjectBelonging(ObjectBelonging value) {
        this.objectBelonging = value;
    }

    /**
     * Gets the value of the configurationExtensionPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationExtensionPurpose }
     *     
     */
    public ConfigurationExtensionPurpose getConfigurationExtensionPurpose() {
        return configurationExtensionPurpose;
    }

    /**
     * Sets the value of the configurationExtensionPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationExtensionPurpose }
     *     
     */
    public void setConfigurationExtensionPurpose(ConfigurationExtensionPurpose value) {
        this.configurationExtensionPurpose = value;
    }

    /**
     * Gets the value of the namePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamePrefix() {
        return namePrefix;
    }

    /**
     * Sets the value of the namePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamePrefix(String value) {
        this.namePrefix = value;
    }

    /**
     * Gets the value of the configurationExtensionCompatibilityMode property.
     * 
     * @return
     *     possible object is
     *     {@link CompatibilityMode }
     *     
     */
    public CompatibilityMode getConfigurationExtensionCompatibilityMode() {
        return configurationExtensionCompatibilityMode;
    }

    /**
     * Sets the value of the configurationExtensionCompatibilityMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompatibilityMode }
     *     
     */
    public void setConfigurationExtensionCompatibilityMode(CompatibilityMode value) {
        this.configurationExtensionCompatibilityMode = value;
    }

    /**
     * Gets the value of the defaultRunMode property.
     * 
     * @return
     *     possible object is
     *     {@link ClientRunMode }
     *     
     */
    public ClientRunMode getDefaultRunMode() {
        return defaultRunMode;
    }

    /**
     * Sets the value of the defaultRunMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientRunMode }
     *     
     */
    public void setDefaultRunMode(ClientRunMode value) {
        this.defaultRunMode = value;
    }

    /**
     * Gets the value of the usePurposes property.
     * 
     * @return
     *     possible object is
     *     {@link FixedArray }
     *     
     */
    public FixedArray getUsePurposes() {
        return usePurposes;
    }

    /**
     * Sets the value of the usePurposes property.
     * 
     * @param value
     *     allowed object is
     *     {@link FixedArray }
     *     
     */
    public void setUsePurposes(FixedArray value) {
        this.usePurposes = value;
    }

    /**
     * Gets the value of the scriptVariant property.
     * 
     * @return
     *     possible object is
     *     {@link ScriptVariant }
     *     
     */
    public ScriptVariant getScriptVariant() {
        return scriptVariant;
    }

    /**
     * Sets the value of the scriptVariant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScriptVariant }
     *     
     */
    public void setScriptVariant(ScriptVariant value) {
        this.scriptVariant = value;
    }

    /**
     * Gets the value of the defaultRoles property.
     * 
     * @return
     *     possible object is
     *     {@link MDListType }
     *     
     */
    public MDListType getDefaultRoles() {
        return defaultRoles;
    }

    /**
     * Sets the value of the defaultRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDListType }
     *     
     */
    public void setDefaultRoles(MDListType value) {
        this.defaultRoles = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendor(String value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the updateCatalogAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateCatalogAddress() {
        return updateCatalogAddress;
    }

    /**
     * Sets the value of the updateCatalogAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateCatalogAddress(String value) {
        this.updateCatalogAddress = value;
    }

    /**
     * Gets the value of the parentConfigurations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentConfigurations() {
        return parentConfigurations;
    }

    /**
     * Sets the value of the parentConfigurations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentConfigurations(String value) {
        this.parentConfigurations = value;
    }

    /**
     * Gets the value of the managedApplicationModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagedApplicationModule() {
        return managedApplicationModule;
    }

    /**
     * Sets the value of the managedApplicationModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagedApplicationModule(String value) {
        this.managedApplicationModule = value;
    }

    /**
     * Gets the value of the sessionModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionModule() {
        return sessionModule;
    }

    /**
     * Sets the value of the sessionModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionModule(String value) {
        this.sessionModule = value;
    }

    /**
     * Gets the value of the externalConnectionModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalConnectionModule() {
        return externalConnectionModule;
    }

    /**
     * Sets the value of the externalConnectionModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalConnectionModule(String value) {
        this.externalConnectionModule = value;
    }

    /**
     * Gets the value of the ordinaryApplicationModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdinaryApplicationModule() {
        return ordinaryApplicationModule;
    }

    /**
     * Sets the value of the ordinaryApplicationModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdinaryApplicationModule(String value) {
        this.ordinaryApplicationModule = value;
    }

    /**
     * Gets the value of the applicationModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationModule() {
        return applicationModule;
    }

    /**
     * Sets the value of the applicationModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationModule(String value) {
        this.applicationModule = value;
    }

    /**
     * Gets the value of the includeHelpInContents property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeHelpInContents() {
        return includeHelpInContents;
    }

    /**
     * Sets the value of the includeHelpInContents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeHelpInContents(Boolean value) {
        this.includeHelpInContents = value;
    }

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelp(String value) {
        this.help = value;
    }

    /**
     * Gets the value of the useManagedFormInOrdinaryApplication property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseManagedFormInOrdinaryApplication() {
        return useManagedFormInOrdinaryApplication;
    }

    /**
     * Sets the value of the useManagedFormInOrdinaryApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseManagedFormInOrdinaryApplication(Boolean value) {
        this.useManagedFormInOrdinaryApplication = value;
    }

    /**
     * Gets the value of the useOrdinaryFormInManagedApplication property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseOrdinaryFormInManagedApplication() {
        return useOrdinaryFormInManagedApplication;
    }

    /**
     * Sets the value of the useOrdinaryFormInManagedApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseOrdinaryFormInManagedApplication(Boolean value) {
        this.useOrdinaryFormInManagedApplication = value;
    }

    /**
     * Gets the value of the additionalFullTextSearchDictionaries property.
     * 
     * @return
     *     possible object is
     *     {@link MDListType }
     *     
     */
    public MDListType getAdditionalFullTextSearchDictionaries() {
        return additionalFullTextSearchDictionaries;
    }

    /**
     * Sets the value of the additionalFullTextSearchDictionaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDListType }
     *     
     */
    public void setAdditionalFullTextSearchDictionaries(MDListType value) {
        this.additionalFullTextSearchDictionaries = value;
    }

    /**
     * Gets the value of the commonSettingsStorage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonSettingsStorage() {
        return commonSettingsStorage;
    }

    /**
     * Sets the value of the commonSettingsStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonSettingsStorage(String value) {
        this.commonSettingsStorage = value;
    }

    /**
     * Gets the value of the reportsUserSettingsStorage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportsUserSettingsStorage() {
        return reportsUserSettingsStorage;
    }

    /**
     * Sets the value of the reportsUserSettingsStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportsUserSettingsStorage(String value) {
        this.reportsUserSettingsStorage = value;
    }

    /**
     * Gets the value of the reportsVariantsStorage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportsVariantsStorage() {
        return reportsVariantsStorage;
    }

    /**
     * Sets the value of the reportsVariantsStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportsVariantsStorage(String value) {
        this.reportsVariantsStorage = value;
    }

    /**
     * Gets the value of the formDataSettingsStorage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormDataSettingsStorage() {
        return formDataSettingsStorage;
    }

    /**
     * Sets the value of the formDataSettingsStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormDataSettingsStorage(String value) {
        this.formDataSettingsStorage = value;
    }

    /**
     * Gets the value of the dynamicListsUserSettingsStorage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDynamicListsUserSettingsStorage() {
        return dynamicListsUserSettingsStorage;
    }

    /**
     * Sets the value of the dynamicListsUserSettingsStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDynamicListsUserSettingsStorage(String value) {
        this.dynamicListsUserSettingsStorage = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link MDListType }
     *     
     */
    public MDListType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDListType }
     *     
     */
    public void setContent(MDListType value) {
        this.content = value;
    }

    /**
     * Gets the value of the defaultReportForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultReportForm() {
        return defaultReportForm;
    }

    /**
     * Sets the value of the defaultReportForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultReportForm(String value) {
        this.defaultReportForm = value;
    }

    /**
     * Gets the value of the defaultReportVariantForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultReportVariantForm() {
        return defaultReportVariantForm;
    }

    /**
     * Sets the value of the defaultReportVariantForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultReportVariantForm(String value) {
        this.defaultReportVariantForm = value;
    }

    /**
     * Gets the value of the defaultReportSettingsForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultReportSettingsForm() {
        return defaultReportSettingsForm;
    }

    /**
     * Sets the value of the defaultReportSettingsForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultReportSettingsForm(String value) {
        this.defaultReportSettingsForm = value;
    }

    /**
     * Gets the value of the defaultDynamicListSettingsForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultDynamicListSettingsForm() {
        return defaultDynamicListSettingsForm;
    }

    /**
     * Sets the value of the defaultDynamicListSettingsForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultDynamicListSettingsForm(String value) {
        this.defaultDynamicListSettingsForm = value;
    }

    /**
     * Gets the value of the defaultSearchForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultSearchForm() {
        return defaultSearchForm;
    }

    /**
     * Sets the value of the defaultSearchForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultSearchForm(String value) {
        this.defaultSearchForm = value;
    }

    /**
     * Gets the value of the requiredMobileApplicationPermissions property.
     * 
     * @return
     *     possible object is
     *     {@link FixedMap }
     *     
     */
    public FixedMap getRequiredMobileApplicationPermissions() {
        return requiredMobileApplicationPermissions;
    }

    /**
     * Sets the value of the requiredMobileApplicationPermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link FixedMap }
     *     
     */
    public void setRequiredMobileApplicationPermissions(FixedMap value) {
        this.requiredMobileApplicationPermissions = value;
    }

    /**
     * Gets the value of the commandInterface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommandInterface() {
        return commandInterface;
    }

    /**
     * Sets the value of the commandInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommandInterface(String value) {
        this.commandInterface = value;
    }

    /**
     * Gets the value of the homePageWorkArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomePageWorkArea() {
        return homePageWorkArea;
    }

    /**
     * Sets the value of the homePageWorkArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomePageWorkArea(String value) {
        this.homePageWorkArea = value;
    }

    /**
     * Gets the value of the startPageWorkingArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartPageWorkingArea() {
        return startPageWorkingArea;
    }

    /**
     * Sets the value of the startPageWorkingArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartPageWorkingArea(String value) {
        this.startPageWorkingArea = value;
    }

    /**
     * Gets the value of the mainSectionCommandInterface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainSectionCommandInterface() {
        return mainSectionCommandInterface;
    }

    /**
     * Sets the value of the mainSectionCommandInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainSectionCommandInterface(String value) {
        this.mainSectionCommandInterface = value;
    }

    /**
     * Gets the value of the mainSectionPicture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainSectionPicture() {
        return mainSectionPicture;
    }

    /**
     * Sets the value of the mainSectionPicture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainSectionPicture(String value) {
        this.mainSectionPicture = value;
    }

    /**
     * Gets the value of the clientApplicationInterface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientApplicationInterface() {
        return clientApplicationInterface;
    }

    /**
     * Sets the value of the clientApplicationInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientApplicationInterface(String value) {
        this.clientApplicationInterface = value;
    }

    /**
     * Gets the value of the mainClientApplicationWindowMode property.
     * 
     * @return
     *     possible object is
     *     {@link MainClientApplicationWindowMode }
     *     
     */
    public MainClientApplicationWindowMode getMainClientApplicationWindowMode() {
        return mainClientApplicationWindowMode;
    }

    /**
     * Sets the value of the mainClientApplicationWindowMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MainClientApplicationWindowMode }
     *     
     */
    public void setMainClientApplicationWindowMode(MainClientApplicationWindowMode value) {
        this.mainClientApplicationWindowMode = value;
    }

    /**
     * Gets the value of the defaultInterface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultInterface() {
        return defaultInterface;
    }

    /**
     * Sets the value of the defaultInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultInterface(String value) {
        this.defaultInterface = value;
    }

    /**
     * Gets the value of the defaultStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultStyle() {
        return defaultStyle;
    }

    /**
     * Sets the value of the defaultStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultStyle(String value) {
        this.defaultStyle = value;
    }

    /**
     * Gets the value of the defaultLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultLanguage() {
        return defaultLanguage;
    }

    /**
     * Sets the value of the defaultLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultLanguage(String value) {
        this.defaultLanguage = value;
    }

    /**
     * Gets the value of the briefInformation property.
     * 
     * @return
     *     possible object is
     *     {@link LocalStringType }
     *     
     */
    public LocalStringType getBriefInformation() {
        return briefInformation;
    }

    /**
     * Sets the value of the briefInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalStringType }
     *     
     */
    public void setBriefInformation(LocalStringType value) {
        this.briefInformation = value;
    }

    /**
     * Gets the value of the detailedInformation property.
     * 
     * @return
     *     possible object is
     *     {@link LocalStringType }
     *     
     */
    public LocalStringType getDetailedInformation() {
        return detailedInformation;
    }

    /**
     * Sets the value of the detailedInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalStringType }
     *     
     */
    public void setDetailedInformation(LocalStringType value) {
        this.detailedInformation = value;
    }

    /**
     * Gets the value of the logo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogo() {
        return logo;
    }

    /**
     * Sets the value of the logo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogo(String value) {
        this.logo = value;
    }

    /**
     * Gets the value of the splash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSplash() {
        return splash;
    }

    /**
     * Sets the value of the splash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSplash(String value) {
        this.splash = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link LocalStringType }
     *     
     */
    public LocalStringType getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalStringType }
     *     
     */
    public void setCopyright(LocalStringType value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the vendorInformationAddress property.
     * 
     * @return
     *     possible object is
     *     {@link LocalStringType }
     *     
     */
    public LocalStringType getVendorInformationAddress() {
        return vendorInformationAddress;
    }

    /**
     * Sets the value of the vendorInformationAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalStringType }
     *     
     */
    public void setVendorInformationAddress(LocalStringType value) {
        this.vendorInformationAddress = value;
    }

    /**
     * Gets the value of the configurationInformationAddress property.
     * 
     * @return
     *     possible object is
     *     {@link LocalStringType }
     *     
     */
    public LocalStringType getConfigurationInformationAddress() {
        return configurationInformationAddress;
    }

    /**
     * Sets the value of the configurationInformationAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalStringType }
     *     
     */
    public void setConfigurationInformationAddress(LocalStringType value) {
        this.configurationInformationAddress = value;
    }

    /**
     * Gets the value of the dataLockControlMode property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultDataLockControlMode }
     *     
     */
    public DefaultDataLockControlMode getDataLockControlMode() {
        return dataLockControlMode;
    }

    /**
     * Sets the value of the dataLockControlMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultDataLockControlMode }
     *     
     */
    public void setDataLockControlMode(DefaultDataLockControlMode value) {
        this.dataLockControlMode = value;
    }

    /**
     * Gets the value of the objectAutonumerationMode property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectAutonumerationMode }
     *     
     */
    public ObjectAutonumerationMode getObjectAutonumerationMode() {
        return objectAutonumerationMode;
    }

    /**
     * Sets the value of the objectAutonumerationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectAutonumerationMode }
     *     
     */
    public void setObjectAutonumerationMode(ObjectAutonumerationMode value) {
        this.objectAutonumerationMode = value;
    }

    /**
     * Gets the value of the modalityUseMode property.
     * 
     * @return
     *     possible object is
     *     {@link ModalityUseMode }
     *     
     */
    public ModalityUseMode getModalityUseMode() {
        return modalityUseMode;
    }

    /**
     * Sets the value of the modalityUseMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModalityUseMode }
     *     
     */
    public void setModalityUseMode(ModalityUseMode value) {
        this.modalityUseMode = value;
    }

    /**
     * Gets the value of the synchronousPlatformExtensionAndAddInCallUseMode property.
     * 
     * @return
     *     possible object is
     *     {@link SynchronousPlatformExtensionAndAddInCallUseMode }
     *     
     */
    public SynchronousPlatformExtensionAndAddInCallUseMode getSynchronousPlatformExtensionAndAddInCallUseMode() {
        return synchronousPlatformExtensionAndAddInCallUseMode;
    }

    /**
     * Sets the value of the synchronousPlatformExtensionAndAddInCallUseMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SynchronousPlatformExtensionAndAddInCallUseMode }
     *     
     */
    public void setSynchronousPlatformExtensionAndAddInCallUseMode(SynchronousPlatformExtensionAndAddInCallUseMode value) {
        this.synchronousPlatformExtensionAndAddInCallUseMode = value;
    }

    /**
     * Gets the value of the synchronousExtensionAndAddInCallUseMode property.
     * 
     * @return
     *     possible object is
     *     {@link SynchronousPlatformExtensionAndAddInCallUseMode }
     *     
     */
    public SynchronousPlatformExtensionAndAddInCallUseMode getSynchronousExtensionAndAddInCallUseMode() {
        return synchronousExtensionAndAddInCallUseMode;
    }

    /**
     * Sets the value of the synchronousExtensionAndAddInCallUseMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SynchronousPlatformExtensionAndAddInCallUseMode }
     *     
     */
    public void setSynchronousExtensionAndAddInCallUseMode(SynchronousPlatformExtensionAndAddInCallUseMode value) {
        this.synchronousExtensionAndAddInCallUseMode = value;
    }

    /**
     * Gets the value of the interfaceCompatibilityMode property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceCompatibilityMode }
     *     
     */
    public InterfaceCompatibilityMode getInterfaceCompatibilityMode() {
        return interfaceCompatibilityMode;
    }

    /**
     * Sets the value of the interfaceCompatibilityMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceCompatibilityMode }
     *     
     */
    public void setInterfaceCompatibilityMode(InterfaceCompatibilityMode value) {
        this.interfaceCompatibilityMode = value;
    }

    /**
     * Gets the value of the compatibilityMode property.
     * 
     * @return
     *     possible object is
     *     {@link CompatibilityMode }
     *     
     */
    public CompatibilityMode getCompatibilityMode() {
        return compatibilityMode;
    }

    /**
     * Sets the value of the compatibilityMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompatibilityMode }
     *     
     */
    public void setCompatibilityMode(CompatibilityMode value) {
        this.compatibilityMode = value;
    }

    /**
     * Gets the value of the defaultConstantsForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultConstantsForm() {
        return defaultConstantsForm;
    }

    /**
     * Sets the value of the defaultConstantsForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultConstantsForm(String value) {
        this.defaultConstantsForm = value;
    }

    /**
     * Gets the value of the defaultConstantForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultConstantForm() {
        return defaultConstantForm;
    }

    /**
     * Sets the value of the defaultConstantForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultConstantForm(String value) {
        this.defaultConstantForm = value;
    }

}
