//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package org.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for DocumentNumeratorProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentNumeratorProperties"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Synonym" type="{http://v8.1c.ru/8.1/data/core}LocalStringType"/&gt;
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ObjectBelonging" type="{http://v8.1c.ru/8.3/xcf/enums}ObjectBelonging"/&gt;
 *         &lt;element name="NumberType" type="{http://v8.1c.ru/8.3/xcf/enums}DocumentNumberType"/&gt;
 *         &lt;element name="NumberLength" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="NumberAllowedLength" type="{http://v8.1c.ru/8.1/data/core}AllowedLength"/&gt;
 *         &lt;element name="NumberPeriodicity" type="{http://v8.1c.ru/8.3/xcf/enums}DocumentNumberPeriodicity"/&gt;
 *         &lt;element name="CheckUnique" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentNumeratorProperties", propOrder = {
    "name",
    "synonym",
    "comment",
    "objectBelonging",
    "numberType",
    "numberLength",
    "numberAllowedLength",
    "numberPeriodicity",
    "checkUnique"
})
public class DocumentNumeratorProperties {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Synonym", required = true)
    protected LocalStringType synonym;
    @XmlElement(name = "Comment", required = true)
    protected String comment;
    @XmlElement(name = "ObjectBelonging", required = true)
    @XmlSchemaType(name = "string")
    protected ObjectBelonging objectBelonging;
    @XmlElement(name = "NumberType", required = true)
    @XmlSchemaType(name = "string")
    protected DocumentNumberType numberType;
    @XmlElement(name = "NumberLength", required = true)
    protected BigDecimal numberLength;
    @XmlElement(name = "NumberAllowedLength", required = true)
    @XmlSchemaType(name = "string")
    protected AllowedLength numberAllowedLength;
    @XmlElement(name = "NumberPeriodicity", required = true)
    @XmlSchemaType(name = "string")
    protected DocumentNumberPeriodicity numberPeriodicity;
    @XmlElement(name = "CheckUnique")
    protected boolean checkUnique;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the synonym property.
     * 
     * @return
     *     possible object is
     *     {@link LocalStringType }
     *     
     */
    public LocalStringType getSynonym() {
        return synonym;
    }

    /**
     * Sets the value of the synonym property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalStringType }
     *     
     */
    public void setSynonym(LocalStringType value) {
        this.synonym = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the objectBelonging property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectBelonging }
     *     
     */
    public ObjectBelonging getObjectBelonging() {
        return objectBelonging;
    }

    /**
     * Sets the value of the objectBelonging property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectBelonging }
     *     
     */
    public void setObjectBelonging(ObjectBelonging value) {
        this.objectBelonging = value;
    }

    /**
     * Gets the value of the numberType property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentNumberType }
     *     
     */
    public DocumentNumberType getNumberType() {
        return numberType;
    }

    /**
     * Sets the value of the numberType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentNumberType }
     *     
     */
    public void setNumberType(DocumentNumberType value) {
        this.numberType = value;
    }

    /**
     * Gets the value of the numberLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumberLength() {
        return numberLength;
    }

    /**
     * Sets the value of the numberLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumberLength(BigDecimal value) {
        this.numberLength = value;
    }

    /**
     * Gets the value of the numberAllowedLength property.
     * 
     * @return
     *     possible object is
     *     {@link AllowedLength }
     *     
     */
    public AllowedLength getNumberAllowedLength() {
        return numberAllowedLength;
    }

    /**
     * Sets the value of the numberAllowedLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllowedLength }
     *     
     */
    public void setNumberAllowedLength(AllowedLength value) {
        this.numberAllowedLength = value;
    }

    /**
     * Gets the value of the numberPeriodicity property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentNumberPeriodicity }
     *     
     */
    public DocumentNumberPeriodicity getNumberPeriodicity() {
        return numberPeriodicity;
    }

    /**
     * Sets the value of the numberPeriodicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentNumberPeriodicity }
     *     
     */
    public void setNumberPeriodicity(DocumentNumberPeriodicity value) {
        this.numberPeriodicity = value;
    }

    /**
     * Gets the value of the checkUnique property.
     * 
     */
    public boolean isCheckUnique() {
        return checkUnique;
    }

    /**
     * Sets the value of the checkUnique property.
     * 
     */
    public void setCheckUnique(boolean value) {
        this.checkUnique = value;
    }

}
