//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package org.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ExtDimensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtDimensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Turnover" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AccountingFlags" type="{http://v8.1c.ru/8.3/xcf/predef}AccountingFlags" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtDimensionType", namespace = "http://v8.1c.ru/8.3/xcf/predef", propOrder = {
    "turnover",
    "accountingFlags"
})
public class ExtDimensionType {

    @XmlElement(name = "Turnover")
    protected boolean turnover;
    @XmlElement(name = "AccountingFlags")
    protected AccountingFlags accountingFlags;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the turnover property.
     * 
     */
    public boolean isTurnover() {
        return turnover;
    }

    /**
     * Sets the value of the turnover property.
     * 
     */
    public void setTurnover(boolean value) {
        this.turnover = value;
    }

    /**
     * Gets the value of the accountingFlags property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingFlags }
     *     
     */
    public AccountingFlags getAccountingFlags() {
        return accountingFlags;
    }

    /**
     * Sets the value of the accountingFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingFlags }
     *     
     */
    public void setAccountingFlags(AccountingFlags value) {
        this.accountingFlags = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
