//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package org.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FillChecking.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FillChecking"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DontCheck"/&gt;
 *     &lt;enumeration value="ShowError"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FillChecking", namespace = "http://v8.1c.ru/8.1/data/core")
@XmlEnum
public enum FillChecking {

    @XmlEnumValue("DontCheck")
    DONT_CHECK("DontCheck"),
    @XmlEnumValue("ShowError")
    SHOW_ERROR("ShowError");
    private final String value;

    FillChecking(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FillChecking fromValue(String v) {
        for (FillChecking c: FillChecking.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
