//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package org.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormChildrenGroup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FormChildrenGroup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Horizontal"/&gt;
 *     &lt;enumeration value="Vertical"/&gt;
 *     &lt;enumeration value="HorizontalIfPossible"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FormChildrenGroup", namespace = "http://v8.1c.ru/8.2/managed-application/logform")
@XmlEnum
public enum FormChildrenGroup {

    @XmlEnumValue("Horizontal")
    HORIZONTAL("Horizontal"),
    @XmlEnumValue("Vertical")
    VERTICAL("Vertical"),
    @XmlEnumValue("HorizontalIfPossible")
    HORIZONTAL_IF_POSSIBLE("HorizontalIfPossible");
    private final String value;

    FormChildrenGroup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FormChildrenGroup fromValue(String v) {
        for (FormChildrenGroup c: FormChildrenGroup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
