//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package org.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OnScreenKeyboardReturnKeyText.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OnScreenKeyboardReturnKeyText"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Auto"/&gt;
 *     &lt;enumeration value="Return"/&gt;
 *     &lt;enumeration value="Go"/&gt;
 *     &lt;enumeration value="Join"/&gt;
 *     &lt;enumeration value="Next"/&gt;
 *     &lt;enumeration value="Search"/&gt;
 *     &lt;enumeration value="Send"/&gt;
 *     &lt;enumeration value="Done"/&gt;
 *     &lt;enumeration value="Continue"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OnScreenKeyboardReturnKeyText", namespace = "http://v8.1c.ru/8.2/managed-application/logform")
@XmlEnum
public enum OnScreenKeyboardReturnKeyText {

    @XmlEnumValue("Auto")
    AUTO("Auto"),
    @XmlEnumValue("Return")
    RETURN("Return"),
    @XmlEnumValue("Go")
    GO("Go"),
    @XmlEnumValue("Join")
    JOIN("Join"),
    @XmlEnumValue("Next")
    NEXT("Next"),
    @XmlEnumValue("Search")
    SEARCH("Search"),
    @XmlEnumValue("Send")
    SEND("Send"),
    @XmlEnumValue("Done")
    DONE("Done"),
    @XmlEnumValue("Continue")
    CONTINUE("Continue");
    private final String value;

    OnScreenKeyboardReturnKeyText(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OnScreenKeyboardReturnKeyText fromValue(String v) {
        for (OnScreenKeyboardReturnKeyText c: OnScreenKeyboardReturnKeyText.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
