//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package org.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for StartInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StartInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="navStartPoint" type="{http://v8.1c.ru/8.2/managed-application/core}NavigationPoint"/&gt;
 *         &lt;element name="subsystemVer" type="{http://v8.1c.ru/8.2/managed-application/core}SubsystemVerInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="desktop" type="{http://v8.1c.ru/8.2/managed-application/core}DesktopInfo"/&gt;
 *         &lt;element name="styleEntries" type="{http://v8.1c.ru/8.2/managed-application/core}StyleEntriesInfo"/&gt;
 *         &lt;element name="fullConfName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="extName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="extIssue" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="compress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="panels" type="{http://v8.1c.ru/8.2/managed-application/core}InterfaceLayouter" minOccurs="0"/&gt;
 *         &lt;element name="choiceHistory" type="{http://v8.1c.ru/8.2/managed-application/core}LFEFChoiceHistory" minOccurs="0"/&gt;
 *         &lt;element name="favs" type="{http://v8.1c.ru/8.2/managed-application/core}UserFavorites" minOccurs="0"/&gt;
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fullUserName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="externalResourceMode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="deploymentType" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="mainWindowMode" type="{http://v8.1c.ru/8.2/managed-application/core}MainWindowMode" /&gt;
 *       &lt;attribute name="infoBaseInstanceID" type="{http://v8.1c.ru/8.1/data/core}UUID" /&gt;
 *       &lt;attribute name="confName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="subsystemsPanelVer" type="{http://v8.1c.ru/8.1/data/core}UUID" /&gt;
 *       &lt;attribute name="foVer" type="{http://v8.1c.ru/8.1/data/core}UUID" /&gt;
 *       &lt;attribute name="mainWindowOptionsVer" type="{http://v8.1c.ru/8.1/data/core}UUID" /&gt;
 *       &lt;attribute name="desktopSpliterPosVer" type="{http://v8.1c.ru/8.1/data/core}UUID" /&gt;
 *       &lt;attribute name="notifyWindowOptionsVer" type="{http://v8.1c.ru/8.1/data/core}UUID" /&gt;
 *       &lt;attribute name="stateWindowOptionsVer" type="{http://v8.1c.ru/8.1/data/core}UUID" /&gt;
 *       &lt;attribute name="commConfName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="commConfURL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="commProvName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="commProvURL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="desktopFormsWindowSettingsVerHash" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="enableOutput" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="allowAllFunctionsMode" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="allowSaveUserData" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="clientSettings" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="debugServerHTTP" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="allowFullTextSearch" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="taxi" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="sdi" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="enableChoiceInterface" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="newInterfaceByDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="largeFont" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StartInfo", namespace = "http://v8.1c.ru/8.2/managed-application/core", propOrder = {
    "navStartPoint",
    "subsystemVer",
    "desktop",
    "styleEntries",
    "fullConfName",
    "extName",
    "extIssue",
    "compress",
    "panels",
    "choiceHistory",
    "favs",
    "userName",
    "fullUserName",
    "externalResourceMode",
    "deploymentType"
})
public class StartInfo {

    @XmlElement(required = true)
    protected NavigationPoint navStartPoint;
    protected List<SubsystemVerInfo> subsystemVer;
    @XmlElement(required = true)
    protected DesktopInfo desktop;
    @XmlElement(required = true)
    protected StyleEntriesInfo styleEntries;
    @XmlElement(required = true)
    protected String fullConfName;
    protected List<String> extName;
    protected List<String> extIssue;
    @XmlElement(required = true)
    protected String compress;
    protected InterfaceLayouter panels;
    protected LFEFChoiceHistory choiceHistory;
    protected UserFavorites favs;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected String fullUserName;
    @XmlElement(required = true)
    protected String externalResourceMode;
    @XmlElement(required = true)
    protected BigDecimal deploymentType;
    @XmlAttribute(name = "mainWindowMode")
    protected MainWindowMode mainWindowMode;
    @XmlAttribute(name = "infoBaseInstanceID")
    protected String infoBaseInstanceID;
    @XmlAttribute(name = "confName")
    protected String confName;
    @XmlAttribute(name = "subsystemsPanelVer")
    protected String subsystemsPanelVer;
    @XmlAttribute(name = "foVer")
    protected String foVer;
    @XmlAttribute(name = "mainWindowOptionsVer")
    protected String mainWindowOptionsVer;
    @XmlAttribute(name = "desktopSpliterPosVer")
    protected String desktopSpliterPosVer;
    @XmlAttribute(name = "notifyWindowOptionsVer")
    protected String notifyWindowOptionsVer;
    @XmlAttribute(name = "stateWindowOptionsVer")
    protected String stateWindowOptionsVer;
    @XmlAttribute(name = "commConfName")
    protected String commConfName;
    @XmlAttribute(name = "commConfURL")
    protected String commConfURL;
    @XmlAttribute(name = "commProvName")
    protected String commProvName;
    @XmlAttribute(name = "commProvURL")
    protected String commProvURL;
    @XmlAttribute(name = "desktopFormsWindowSettingsVerHash")
    protected String desktopFormsWindowSettingsVerHash;
    @XmlAttribute(name = "enableOutput")
    protected Boolean enableOutput;
    @XmlAttribute(name = "allowAllFunctionsMode")
    protected Boolean allowAllFunctionsMode;
    @XmlAttribute(name = "allowSaveUserData")
    protected Boolean allowSaveUserData;
    @XmlAttribute(name = "clientSettings")
    protected BigDecimal clientSettings;
    @XmlAttribute(name = "debugServerHTTP")
    protected String debugServerHTTP;
    @XmlAttribute(name = "allowFullTextSearch")
    protected Boolean allowFullTextSearch;
    @XmlAttribute(name = "taxi")
    protected Boolean taxi;
    @XmlAttribute(name = "sdi")
    protected Boolean sdi;
    @XmlAttribute(name = "enableChoiceInterface")
    protected Boolean enableChoiceInterface;
    @XmlAttribute(name = "newInterfaceByDefault")
    protected Boolean newInterfaceByDefault;
    @XmlAttribute(name = "largeFont")
    protected Boolean largeFont;

    /**
     * Gets the value of the navStartPoint property.
     * 
     * @return
     *     possible object is
     *     {@link NavigationPoint }
     *     
     */
    public NavigationPoint getNavStartPoint() {
        return navStartPoint;
    }

    /**
     * Sets the value of the navStartPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavigationPoint }
     *     
     */
    public void setNavStartPoint(NavigationPoint value) {
        this.navStartPoint = value;
    }

    /**
     * Gets the value of the subsystemVer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subsystemVer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubsystemVer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubsystemVerInfo }
     * 
     * 
     */
    public List<SubsystemVerInfo> getSubsystemVer() {
        if (subsystemVer == null) {
            subsystemVer = new ArrayList<SubsystemVerInfo>();
        }
        return this.subsystemVer;
    }

    /**
     * Gets the value of the desktop property.
     * 
     * @return
     *     possible object is
     *     {@link DesktopInfo }
     *     
     */
    public DesktopInfo getDesktop() {
        return desktop;
    }

    /**
     * Sets the value of the desktop property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesktopInfo }
     *     
     */
    public void setDesktop(DesktopInfo value) {
        this.desktop = value;
    }

    /**
     * Gets the value of the styleEntries property.
     * 
     * @return
     *     possible object is
     *     {@link StyleEntriesInfo }
     *     
     */
    public StyleEntriesInfo getStyleEntries() {
        return styleEntries;
    }

    /**
     * Sets the value of the styleEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link StyleEntriesInfo }
     *     
     */
    public void setStyleEntries(StyleEntriesInfo value) {
        this.styleEntries = value;
    }

    /**
     * Gets the value of the fullConfName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullConfName() {
        return fullConfName;
    }

    /**
     * Sets the value of the fullConfName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullConfName(String value) {
        this.fullConfName = value;
    }

    /**
     * Gets the value of the extName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExtName() {
        if (extName == null) {
            extName = new ArrayList<String>();
        }
        return this.extName;
    }

    /**
     * Gets the value of the extIssue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extIssue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtIssue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExtIssue() {
        if (extIssue == null) {
            extIssue = new ArrayList<String>();
        }
        return this.extIssue;
    }

    /**
     * Gets the value of the compress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompress() {
        return compress;
    }

    /**
     * Sets the value of the compress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompress(String value) {
        this.compress = value;
    }

    /**
     * Gets the value of the panels property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceLayouter }
     *     
     */
    public InterfaceLayouter getPanels() {
        return panels;
    }

    /**
     * Sets the value of the panels property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceLayouter }
     *     
     */
    public void setPanels(InterfaceLayouter value) {
        this.panels = value;
    }

    /**
     * Gets the value of the choiceHistory property.
     * 
     * @return
     *     possible object is
     *     {@link LFEFChoiceHistory }
     *     
     */
    public LFEFChoiceHistory getChoiceHistory() {
        return choiceHistory;
    }

    /**
     * Sets the value of the choiceHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link LFEFChoiceHistory }
     *     
     */
    public void setChoiceHistory(LFEFChoiceHistory value) {
        this.choiceHistory = value;
    }

    /**
     * Gets the value of the favs property.
     * 
     * @return
     *     possible object is
     *     {@link UserFavorites }
     *     
     */
    public UserFavorites getFavs() {
        return favs;
    }

    /**
     * Sets the value of the favs property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFavorites }
     *     
     */
    public void setFavs(UserFavorites value) {
        this.favs = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the fullUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullUserName() {
        return fullUserName;
    }

    /**
     * Sets the value of the fullUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullUserName(String value) {
        this.fullUserName = value;
    }

    /**
     * Gets the value of the externalResourceMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalResourceMode() {
        return externalResourceMode;
    }

    /**
     * Sets the value of the externalResourceMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalResourceMode(String value) {
        this.externalResourceMode = value;
    }

    /**
     * Gets the value of the deploymentType property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDeploymentType() {
        return deploymentType;
    }

    /**
     * Sets the value of the deploymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDeploymentType(BigDecimal value) {
        this.deploymentType = value;
    }

    /**
     * Gets the value of the mainWindowMode property.
     * 
     * @return
     *     possible object is
     *     {@link MainWindowMode }
     *     
     */
    public MainWindowMode getMainWindowMode() {
        return mainWindowMode;
    }

    /**
     * Sets the value of the mainWindowMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MainWindowMode }
     *     
     */
    public void setMainWindowMode(MainWindowMode value) {
        this.mainWindowMode = value;
    }

    /**
     * Gets the value of the infoBaseInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfoBaseInstanceID() {
        return infoBaseInstanceID;
    }

    /**
     * Sets the value of the infoBaseInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfoBaseInstanceID(String value) {
        this.infoBaseInstanceID = value;
    }

    /**
     * Gets the value of the confName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfName() {
        return confName;
    }

    /**
     * Sets the value of the confName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfName(String value) {
        this.confName = value;
    }

    /**
     * Gets the value of the subsystemsPanelVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsystemsPanelVer() {
        return subsystemsPanelVer;
    }

    /**
     * Sets the value of the subsystemsPanelVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsystemsPanelVer(String value) {
        this.subsystemsPanelVer = value;
    }

    /**
     * Gets the value of the foVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoVer() {
        return foVer;
    }

    /**
     * Sets the value of the foVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoVer(String value) {
        this.foVer = value;
    }

    /**
     * Gets the value of the mainWindowOptionsVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainWindowOptionsVer() {
        return mainWindowOptionsVer;
    }

    /**
     * Sets the value of the mainWindowOptionsVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainWindowOptionsVer(String value) {
        this.mainWindowOptionsVer = value;
    }

    /**
     * Gets the value of the desktopSpliterPosVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesktopSpliterPosVer() {
        return desktopSpliterPosVer;
    }

    /**
     * Sets the value of the desktopSpliterPosVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesktopSpliterPosVer(String value) {
        this.desktopSpliterPosVer = value;
    }

    /**
     * Gets the value of the notifyWindowOptionsVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotifyWindowOptionsVer() {
        return notifyWindowOptionsVer;
    }

    /**
     * Sets the value of the notifyWindowOptionsVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotifyWindowOptionsVer(String value) {
        this.notifyWindowOptionsVer = value;
    }

    /**
     * Gets the value of the stateWindowOptionsVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateWindowOptionsVer() {
        return stateWindowOptionsVer;
    }

    /**
     * Sets the value of the stateWindowOptionsVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateWindowOptionsVer(String value) {
        this.stateWindowOptionsVer = value;
    }

    /**
     * Gets the value of the commConfName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommConfName() {
        return commConfName;
    }

    /**
     * Sets the value of the commConfName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommConfName(String value) {
        this.commConfName = value;
    }

    /**
     * Gets the value of the commConfURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommConfURL() {
        return commConfURL;
    }

    /**
     * Sets the value of the commConfURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommConfURL(String value) {
        this.commConfURL = value;
    }

    /**
     * Gets the value of the commProvName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommProvName() {
        return commProvName;
    }

    /**
     * Sets the value of the commProvName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommProvName(String value) {
        this.commProvName = value;
    }

    /**
     * Gets the value of the commProvURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommProvURL() {
        return commProvURL;
    }

    /**
     * Sets the value of the commProvURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommProvURL(String value) {
        this.commProvURL = value;
    }

    /**
     * Gets the value of the desktopFormsWindowSettingsVerHash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesktopFormsWindowSettingsVerHash() {
        return desktopFormsWindowSettingsVerHash;
    }

    /**
     * Sets the value of the desktopFormsWindowSettingsVerHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesktopFormsWindowSettingsVerHash(String value) {
        this.desktopFormsWindowSettingsVerHash = value;
    }

    /**
     * Gets the value of the enableOutput property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableOutput() {
        return enableOutput;
    }

    /**
     * Sets the value of the enableOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableOutput(Boolean value) {
        this.enableOutput = value;
    }

    /**
     * Gets the value of the allowAllFunctionsMode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowAllFunctionsMode() {
        return allowAllFunctionsMode;
    }

    /**
     * Sets the value of the allowAllFunctionsMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowAllFunctionsMode(Boolean value) {
        this.allowAllFunctionsMode = value;
    }

    /**
     * Gets the value of the allowSaveUserData property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowSaveUserData() {
        return allowSaveUserData;
    }

    /**
     * Sets the value of the allowSaveUserData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowSaveUserData(Boolean value) {
        this.allowSaveUserData = value;
    }

    /**
     * Gets the value of the clientSettings property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getClientSettings() {
        return clientSettings;
    }

    /**
     * Sets the value of the clientSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setClientSettings(BigDecimal value) {
        this.clientSettings = value;
    }

    /**
     * Gets the value of the debugServerHTTP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebugServerHTTP() {
        return debugServerHTTP;
    }

    /**
     * Sets the value of the debugServerHTTP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebugServerHTTP(String value) {
        this.debugServerHTTP = value;
    }

    /**
     * Gets the value of the allowFullTextSearch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowFullTextSearch() {
        return allowFullTextSearch;
    }

    /**
     * Sets the value of the allowFullTextSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowFullTextSearch(Boolean value) {
        this.allowFullTextSearch = value;
    }

    /**
     * Gets the value of the taxi property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxi() {
        return taxi;
    }

    /**
     * Sets the value of the taxi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxi(Boolean value) {
        this.taxi = value;
    }

    /**
     * Gets the value of the sdi property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSdi() {
        return sdi;
    }

    /**
     * Sets the value of the sdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSdi(Boolean value) {
        this.sdi = value;
    }

    /**
     * Gets the value of the enableChoiceInterface property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableChoiceInterface() {
        return enableChoiceInterface;
    }

    /**
     * Sets the value of the enableChoiceInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableChoiceInterface(Boolean value) {
        this.enableChoiceInterface = value;
    }

    /**
     * Gets the value of the newInterfaceByDefault property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNewInterfaceByDefault() {
        return newInterfaceByDefault;
    }

    /**
     * Sets the value of the newInterfaceByDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNewInterfaceByDefault(Boolean value) {
        this.newInterfaceByDefault = value;
    }

    /**
     * Gets the value of the largeFont property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLargeFont() {
        return largeFont;
    }

    /**
     * Sets the value of the largeFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLargeFont(Boolean value) {
        this.largeFont = value;
    }

}
