//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package org.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for TableLogForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TableLogForm"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="prop" type="{http://v8.1c.ru/8.2/managed-application/logform}DataPath" minOccurs="0"/&gt;
 *         &lt;element name="propName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tdp" type="{http://v8.1c.ru/8.1/data/core}TypeDescription" minOccurs="0"/&gt;
 *         &lt;element name="rowsPicProp" type="{http://v8.1c.ru/8.2/managed-application/logform}DataPath" minOccurs="0"/&gt;
 *         &lt;element name="rowsPicPropName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rowsPic" type="{http://v8.1c.ru/8.1/data/ui}Picture" minOccurs="0"/&gt;
 *         &lt;element name="bkClr" type="{http://v8.1c.ru/8.1/data/ui}Color" minOccurs="0"/&gt;
 *         &lt;element name="txtClr" type="{http://v8.1c.ru/8.1/data/ui}Color" minOccurs="0"/&gt;
 *         &lt;element name="brdClr" type="{http://v8.1c.ru/8.1/data/ui}Color" minOccurs="0"/&gt;
 *         &lt;element name="fnt" type="{http://v8.1c.ru/8.1/data/ui}Font" minOccurs="0"/&gt;
 *         &lt;element name="titleTxtClr" type="{http://v8.1c.ru/8.1/data/ui}Color" minOccurs="0"/&gt;
 *         &lt;element name="titleFnt" type="{http://v8.1c.ru/8.1/data/ui}Font" minOccurs="0"/&gt;
 *         &lt;element name="stcut" type="{http://v8.1c.ru/8.1/data/ui}ShortCutType" minOccurs="0"/&gt;
 *         &lt;element name="addProps" type="{http://v8.1c.ru/8.2/managed-application/logform}AddProps" minOccurs="0"/&gt;
 *         &lt;element name="event" type="{http://v8.1c.ru/8.2/managed-application/logform}Event" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="commands" type="{http://v8.1c.ru/8.2/managed-application/logform}CommandsInclusion"/&gt;
 *         &lt;element name="predefined" type="{http://v8.1c.ru/8.2/managed-application/logform}Predefined" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="field" type="{http://v8.1c.ru/8.2/managed-application/logform}FieldLogForm" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="group" type="{http://v8.1c.ru/8.2/managed-application/logform}GroupLogForm" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tooltip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="org" type="{http://v8.1c.ru/8.2/managed-application/logform}FormElementOrigin" /&gt;
 *       &lt;attribute name="repres" type="{http://v8.1c.ru/8.2/managed-application/logform}TableRepresentation" /&gt;
 *       &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="userVisible" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="titleLocation" type="{http://v8.1c.ru/8.2/managed-application/logform}FormElementTitleLocation" /&gt;
 *       &lt;attribute name="titleRowsCount" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="commandBarLocation" type="{http://v8.1c.ru/8.2/managed-application/logform}FormElementCommandBarLocation" /&gt;
 *       &lt;attribute name="autoFill" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="readOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="skipOnInput" type="{http://v8.1c.ru/8.2/managed-application/logform}BWAValue" /&gt;
 *       &lt;attribute name="defItem" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="changeRowSet" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="changeRowOrder" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="rowsCount" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="heightControlVariant" type="{http://v8.1c.ru/8.2/managed-application/logform}TableHeightControlVariant" /&gt;
 *       &lt;attribute name="autoMaxRowsCount" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="maxRowsCount" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="autoMaxWidth" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="maxWidth" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="minWidth" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="autoMaxHeight" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="maxHeight" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="choiceMode" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="multipleChoice" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="rowInput" type="{http://v8.1c.ru/8.2/managed-application/logform}TableRowInputMode" /&gt;
 *       &lt;attribute name="rowsSelection" type="{http://v8.1c.ru/8.2/managed-application/logform}TableSelectionMode" /&gt;
 *       &lt;attribute name="rowSelection" type="{http://v8.1c.ru/8.2/managed-application/logform}TableRowSelectionMode" /&gt;
 *       &lt;attribute name="showHeader" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="headerHeight" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="showFooter" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="footerHeight" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="horScroll" type="{http://v8.1c.ru/8.2/managed-application/logform}TableScrollBarUse" /&gt;
 *       &lt;attribute name="verScroll" type="{http://v8.1c.ru/8.2/managed-application/logform}TableScrollBarUse" /&gt;
 *       &lt;attribute name="showHorLines" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="showVerLines" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="fixedLeft" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="fixedRight" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="useAltRowColor" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="autoInsert" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="autoInsertNotcompleted" type="{http://v8.1c.ru/8.2/managed-application/logform}BWAValue" /&gt;
 *       &lt;attribute name="autoMarkNotcompleted" type="{http://v8.1c.ru/8.2/managed-application/logform}BWAValue" /&gt;
 *       &lt;attribute name="searchOnInput" type="{http://v8.1c.ru/8.2/managed-application/logform}SearchOnInput" /&gt;
 *       &lt;attribute name="initListView" type="{http://v8.1c.ru/8.2/managed-application/logform}TableInitialListView" /&gt;
 *       &lt;attribute name="initTreeView" type="{http://v8.1c.ru/8.2/managed-application/logform}TableInitialTreeView" /&gt;
 *       &lt;attribute name="useOutput" type="{http://v8.1c.ru/8.1/data/ui}UseOutput" /&gt;
 *       &lt;attribute name="horStretch" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="verStretch" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="startDrag" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="drag" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="tooltipRepres" type="{http://v8.1c.ru/8.2/managed-application/logform}TooltipRepresentation" /&gt;
 *       &lt;attribute name="searchStringLocation" type="{http://v8.1c.ru/8.2/managed-application/logform}SearchStringLocation" /&gt;
 *       &lt;attribute name="viewStatusLocation" type="{http://v8.1c.ru/8.2/managed-application/logform}ViewStatusLocation" /&gt;
 *       &lt;attribute name="searchControlLocation" type="{http://v8.1c.ru/8.2/managed-application/logform}SearchControlLocation" /&gt;
 *       &lt;attribute name="groupHAlign" type="{http://v8.1c.ru/8.2/managed-application/logform}ItemHorizontalAlignment" /&gt;
 *       &lt;attribute name="groupVAlign" type="{http://v8.1c.ru/8.2/managed-application/logform}ItemVerticalAlignment" /&gt;
 *       &lt;attribute name="clearEvents" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="refreshRequest" type="{http://v8.1c.ru/8.2/managed-application/logform}RefreshRequestMethod" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TableLogForm", namespace = "http://v8.1c.ru/8.2/managed-application/logform", propOrder = {
    "prop",
    "propName",
    "tdp",
    "rowsPicProp",
    "rowsPicPropName",
    "rowsPic",
    "bkClr",
    "txtClr",
    "brdClr",
    "fnt",
    "titleTxtClr",
    "titleFnt",
    "stcut",
    "addProps",
    "event",
    "commands",
    "predefined",
    "field",
    "group",
    "title",
    "tooltip"
})
public class TableLogForm {

    protected DataPath prop;
    protected String propName;
    protected TypeDescription tdp;
    protected DataPath rowsPicProp;
    protected String rowsPicPropName;
    protected Picture rowsPic;
    @XmlSchemaType(name = "anySimpleType")
    protected String bkClr;
    @XmlSchemaType(name = "anySimpleType")
    protected String txtClr;
    @XmlSchemaType(name = "anySimpleType")
    protected String brdClr;
    protected Font fnt;
    @XmlSchemaType(name = "anySimpleType")
    protected String titleTxtClr;
    protected Font titleFnt;
    protected ShortCutType stcut;
    protected AddProps addProps;
    protected List<Event> event;
    protected CommandsInclusion commands;
    protected List<Predefined> predefined;
    protected List<FieldLogForm> field;
    protected List<GroupLogForm> group;
    protected String title;
    protected String tooltip;
    @XmlAttribute(name = "id")
    protected BigDecimal id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "org")
    protected FormElementOrigin org;
    @XmlAttribute(name = "repres")
    protected TableRepresentation repres;
    @XmlAttribute(name = "visible")
    protected Boolean visible;
    @XmlAttribute(name = "userVisible")
    protected Boolean userVisible;
    @XmlAttribute(name = "titleLocation")
    protected FormElementTitleLocation titleLocation;
    @XmlAttribute(name = "titleRowsCount")
    protected BigDecimal titleRowsCount;
    @XmlAttribute(name = "commandBarLocation")
    protected FormElementCommandBarLocation commandBarLocation;
    @XmlAttribute(name = "autoFill")
    protected Boolean autoFill;
    @XmlAttribute(name = "enabled")
    protected Boolean enabled;
    @XmlAttribute(name = "readOnly")
    protected Boolean readOnly;
    @XmlAttribute(name = "skipOnInput")
    protected BWAValue skipOnInput;
    @XmlAttribute(name = "defItem")
    protected Boolean defItem;
    @XmlAttribute(name = "changeRowSet")
    protected Boolean changeRowSet;
    @XmlAttribute(name = "changeRowOrder")
    protected Boolean changeRowOrder;
    @XmlAttribute(name = "width")
    protected BigDecimal width;
    @XmlAttribute(name = "height")
    protected BigDecimal height;
    @XmlAttribute(name = "rowsCount")
    protected BigDecimal rowsCount;
    @XmlAttribute(name = "heightControlVariant")
    protected TableHeightControlVariant heightControlVariant;
    @XmlAttribute(name = "autoMaxRowsCount")
    protected Boolean autoMaxRowsCount;
    @XmlAttribute(name = "maxRowsCount")
    protected BigDecimal maxRowsCount;
    @XmlAttribute(name = "autoMaxWidth")
    protected Boolean autoMaxWidth;
    @XmlAttribute(name = "maxWidth")
    protected BigDecimal maxWidth;
    @XmlAttribute(name = "minWidth")
    protected BigDecimal minWidth;
    @XmlAttribute(name = "autoMaxHeight")
    protected Boolean autoMaxHeight;
    @XmlAttribute(name = "maxHeight")
    protected BigDecimal maxHeight;
    @XmlAttribute(name = "choiceMode")
    protected Boolean choiceMode;
    @XmlAttribute(name = "multipleChoice")
    protected Boolean multipleChoice;
    @XmlAttribute(name = "rowInput")
    protected TableRowInputMode rowInput;
    @XmlAttribute(name = "rowsSelection")
    protected TableSelectionMode rowsSelection;
    @XmlAttribute(name = "rowSelection")
    protected TableRowSelectionMode rowSelection;
    @XmlAttribute(name = "showHeader")
    protected Boolean showHeader;
    @XmlAttribute(name = "headerHeight")
    protected BigDecimal headerHeight;
    @XmlAttribute(name = "showFooter")
    protected Boolean showFooter;
    @XmlAttribute(name = "footerHeight")
    protected BigDecimal footerHeight;
    @XmlAttribute(name = "horScroll")
    protected TableScrollBarUse horScroll;
    @XmlAttribute(name = "verScroll")
    protected TableScrollBarUse verScroll;
    @XmlAttribute(name = "showHorLines")
    protected Boolean showHorLines;
    @XmlAttribute(name = "showVerLines")
    protected Boolean showVerLines;
    @XmlAttribute(name = "fixedLeft")
    protected BigDecimal fixedLeft;
    @XmlAttribute(name = "fixedRight")
    protected BigDecimal fixedRight;
    @XmlAttribute(name = "useAltRowColor")
    protected Boolean useAltRowColor;
    @XmlAttribute(name = "autoInsert")
    protected Boolean autoInsert;
    @XmlAttribute(name = "autoInsertNotcompleted")
    protected BWAValue autoInsertNotcompleted;
    @XmlAttribute(name = "autoMarkNotcompleted")
    protected BWAValue autoMarkNotcompleted;
    @XmlAttribute(name = "searchOnInput")
    protected SearchOnInput searchOnInput;
    @XmlAttribute(name = "initListView")
    protected TableInitialListView initListView;
    @XmlAttribute(name = "initTreeView")
    protected TableInitialTreeView initTreeView;
    @XmlAttribute(name = "useOutput")
    protected UseOutput useOutput;
    @XmlAttribute(name = "horStretch")
    protected Boolean horStretch;
    @XmlAttribute(name = "verStretch")
    protected Boolean verStretch;
    @XmlAttribute(name = "startDrag")
    protected Boolean startDrag;
    @XmlAttribute(name = "drag")
    protected Boolean drag;
    @XmlAttribute(name = "tooltipRepres")
    protected TooltipRepresentation tooltipRepres;
    @XmlAttribute(name = "searchStringLocation")
    protected SearchStringLocation searchStringLocation;
    @XmlAttribute(name = "viewStatusLocation")
    protected ViewStatusLocation viewStatusLocation;
    @XmlAttribute(name = "searchControlLocation")
    protected SearchControlLocation searchControlLocation;
    @XmlAttribute(name = "groupHAlign")
    protected ItemHorizontalAlignment groupHAlign;
    @XmlAttribute(name = "groupVAlign")
    protected ItemVerticalAlignment groupVAlign;
    @XmlAttribute(name = "clearEvents")
    protected Boolean clearEvents;
    @XmlAttribute(name = "refreshRequest")
    protected RefreshRequestMethod refreshRequest;

    /**
     * Gets the value of the prop property.
     * 
     * @return
     *     possible object is
     *     {@link DataPath }
     *     
     */
    public DataPath getProp() {
        return prop;
    }

    /**
     * Sets the value of the prop property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataPath }
     *     
     */
    public void setProp(DataPath value) {
        this.prop = value;
    }

    /**
     * Gets the value of the propName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropName() {
        return propName;
    }

    /**
     * Sets the value of the propName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropName(String value) {
        this.propName = value;
    }

    /**
     * Gets the value of the tdp property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDescription }
     *     
     */
    public TypeDescription getTdp() {
        return tdp;
    }

    /**
     * Sets the value of the tdp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDescription }
     *     
     */
    public void setTdp(TypeDescription value) {
        this.tdp = value;
    }

    /**
     * Gets the value of the rowsPicProp property.
     * 
     * @return
     *     possible object is
     *     {@link DataPath }
     *     
     */
    public DataPath getRowsPicProp() {
        return rowsPicProp;
    }

    /**
     * Sets the value of the rowsPicProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataPath }
     *     
     */
    public void setRowsPicProp(DataPath value) {
        this.rowsPicProp = value;
    }

    /**
     * Gets the value of the rowsPicPropName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowsPicPropName() {
        return rowsPicPropName;
    }

    /**
     * Sets the value of the rowsPicPropName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowsPicPropName(String value) {
        this.rowsPicPropName = value;
    }

    /**
     * Gets the value of the rowsPic property.
     * 
     * @return
     *     possible object is
     *     {@link Picture }
     *     
     */
    public Picture getRowsPic() {
        return rowsPic;
    }

    /**
     * Sets the value of the rowsPic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Picture }
     *     
     */
    public void setRowsPic(Picture value) {
        this.rowsPic = value;
    }

    /**
     * Gets the value of the bkClr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBkClr() {
        return bkClr;
    }

    /**
     * Sets the value of the bkClr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBkClr(String value) {
        this.bkClr = value;
    }

    /**
     * Gets the value of the txtClr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxtClr() {
        return txtClr;
    }

    /**
     * Sets the value of the txtClr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxtClr(String value) {
        this.txtClr = value;
    }

    /**
     * Gets the value of the brdClr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrdClr() {
        return brdClr;
    }

    /**
     * Sets the value of the brdClr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrdClr(String value) {
        this.brdClr = value;
    }

    /**
     * Gets the value of the fnt property.
     * 
     * @return
     *     possible object is
     *     {@link Font }
     *     
     */
    public Font getFnt() {
        return fnt;
    }

    /**
     * Sets the value of the fnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Font }
     *     
     */
    public void setFnt(Font value) {
        this.fnt = value;
    }

    /**
     * Gets the value of the titleTxtClr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleTxtClr() {
        return titleTxtClr;
    }

    /**
     * Sets the value of the titleTxtClr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleTxtClr(String value) {
        this.titleTxtClr = value;
    }

    /**
     * Gets the value of the titleFnt property.
     * 
     * @return
     *     possible object is
     *     {@link Font }
     *     
     */
    public Font getTitleFnt() {
        return titleFnt;
    }

    /**
     * Sets the value of the titleFnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Font }
     *     
     */
    public void setTitleFnt(Font value) {
        this.titleFnt = value;
    }

    /**
     * Gets the value of the stcut property.
     * 
     * @return
     *     possible object is
     *     {@link ShortCutType }
     *     
     */
    public ShortCutType getStcut() {
        return stcut;
    }

    /**
     * Sets the value of the stcut property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShortCutType }
     *     
     */
    public void setStcut(ShortCutType value) {
        this.stcut = value;
    }

    /**
     * Gets the value of the addProps property.
     * 
     * @return
     *     possible object is
     *     {@link AddProps }
     *     
     */
    public AddProps getAddProps() {
        return addProps;
    }

    /**
     * Sets the value of the addProps property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddProps }
     *     
     */
    public void setAddProps(AddProps value) {
        this.addProps = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the event property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Event }
     * 
     * 
     */
    public List<Event> getEvent() {
        if (event == null) {
            event = new ArrayList<Event>();
        }
        return this.event;
    }

    /**
     * Gets the value of the commands property.
     * 
     * @return
     *     possible object is
     *     {@link CommandsInclusion }
     *     
     */
    public CommandsInclusion getCommands() {
        return commands;
    }

    /**
     * Sets the value of the commands property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommandsInclusion }
     *     
     */
    public void setCommands(CommandsInclusion value) {
        this.commands = value;
    }

    /**
     * Gets the value of the predefined property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the predefined property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPredefined().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Predefined }
     * 
     * 
     */
    public List<Predefined> getPredefined() {
        if (predefined == null) {
            predefined = new ArrayList<Predefined>();
        }
        return this.predefined;
    }

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldLogForm }
     * 
     * 
     */
    public List<FieldLogForm> getField() {
        if (field == null) {
            field = new ArrayList<FieldLogForm>();
        }
        return this.field;
    }

    /**
     * Gets the value of the group property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the group property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupLogForm }
     * 
     * 
     */
    public List<GroupLogForm> getGroup() {
        if (group == null) {
            group = new ArrayList<GroupLogForm>();
        }
        return this.group;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the tooltip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTooltip() {
        return tooltip;
    }

    /**
     * Sets the value of the tooltip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTooltip(String value) {
        this.tooltip = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setId(BigDecimal value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the org property.
     * 
     * @return
     *     possible object is
     *     {@link FormElementOrigin }
     *     
     */
    public FormElementOrigin getOrg() {
        return org;
    }

    /**
     * Sets the value of the org property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormElementOrigin }
     *     
     */
    public void setOrg(FormElementOrigin value) {
        this.org = value;
    }

    /**
     * Gets the value of the repres property.
     * 
     * @return
     *     possible object is
     *     {@link TableRepresentation }
     *     
     */
    public TableRepresentation getRepres() {
        return repres;
    }

    /**
     * Sets the value of the repres property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableRepresentation }
     *     
     */
    public void setRepres(TableRepresentation value) {
        this.repres = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

    /**
     * Gets the value of the userVisible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUserVisible() {
        return userVisible;
    }

    /**
     * Sets the value of the userVisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserVisible(Boolean value) {
        this.userVisible = value;
    }

    /**
     * Gets the value of the titleLocation property.
     * 
     * @return
     *     possible object is
     *     {@link FormElementTitleLocation }
     *     
     */
    public FormElementTitleLocation getTitleLocation() {
        return titleLocation;
    }

    /**
     * Sets the value of the titleLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormElementTitleLocation }
     *     
     */
    public void setTitleLocation(FormElementTitleLocation value) {
        this.titleLocation = value;
    }

    /**
     * Gets the value of the titleRowsCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTitleRowsCount() {
        return titleRowsCount;
    }

    /**
     * Sets the value of the titleRowsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTitleRowsCount(BigDecimal value) {
        this.titleRowsCount = value;
    }

    /**
     * Gets the value of the commandBarLocation property.
     * 
     * @return
     *     possible object is
     *     {@link FormElementCommandBarLocation }
     *     
     */
    public FormElementCommandBarLocation getCommandBarLocation() {
        return commandBarLocation;
    }

    /**
     * Sets the value of the commandBarLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormElementCommandBarLocation }
     *     
     */
    public void setCommandBarLocation(FormElementCommandBarLocation value) {
        this.commandBarLocation = value;
    }

    /**
     * Gets the value of the autoFill property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoFill() {
        return autoFill;
    }

    /**
     * Sets the value of the autoFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoFill(Boolean value) {
        this.autoFill = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the readOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReadOnly() {
        return readOnly;
    }

    /**
     * Sets the value of the readOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReadOnly(Boolean value) {
        this.readOnly = value;
    }

    /**
     * Gets the value of the skipOnInput property.
     * 
     * @return
     *     possible object is
     *     {@link BWAValue }
     *     
     */
    public BWAValue getSkipOnInput() {
        return skipOnInput;
    }

    /**
     * Sets the value of the skipOnInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link BWAValue }
     *     
     */
    public void setSkipOnInput(BWAValue value) {
        this.skipOnInput = value;
    }

    /**
     * Gets the value of the defItem property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDefItem() {
        return defItem;
    }

    /**
     * Sets the value of the defItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefItem(Boolean value) {
        this.defItem = value;
    }

    /**
     * Gets the value of the changeRowSet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isChangeRowSet() {
        return changeRowSet;
    }

    /**
     * Sets the value of the changeRowSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChangeRowSet(Boolean value) {
        this.changeRowSet = value;
    }

    /**
     * Gets the value of the changeRowOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isChangeRowOrder() {
        return changeRowOrder;
    }

    /**
     * Sets the value of the changeRowOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChangeRowOrder(Boolean value) {
        this.changeRowOrder = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWidth(BigDecimal value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHeight(BigDecimal value) {
        this.height = value;
    }

    /**
     * Gets the value of the rowsCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRowsCount() {
        return rowsCount;
    }

    /**
     * Sets the value of the rowsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRowsCount(BigDecimal value) {
        this.rowsCount = value;
    }

    /**
     * Gets the value of the heightControlVariant property.
     * 
     * @return
     *     possible object is
     *     {@link TableHeightControlVariant }
     *     
     */
    public TableHeightControlVariant getHeightControlVariant() {
        return heightControlVariant;
    }

    /**
     * Sets the value of the heightControlVariant property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableHeightControlVariant }
     *     
     */
    public void setHeightControlVariant(TableHeightControlVariant value) {
        this.heightControlVariant = value;
    }

    /**
     * Gets the value of the autoMaxRowsCount property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoMaxRowsCount() {
        return autoMaxRowsCount;
    }

    /**
     * Sets the value of the autoMaxRowsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoMaxRowsCount(Boolean value) {
        this.autoMaxRowsCount = value;
    }

    /**
     * Gets the value of the maxRowsCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxRowsCount() {
        return maxRowsCount;
    }

    /**
     * Sets the value of the maxRowsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxRowsCount(BigDecimal value) {
        this.maxRowsCount = value;
    }

    /**
     * Gets the value of the autoMaxWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoMaxWidth() {
        return autoMaxWidth;
    }

    /**
     * Sets the value of the autoMaxWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoMaxWidth(Boolean value) {
        this.autoMaxWidth = value;
    }

    /**
     * Gets the value of the maxWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxWidth() {
        return maxWidth;
    }

    /**
     * Sets the value of the maxWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxWidth(BigDecimal value) {
        this.maxWidth = value;
    }

    /**
     * Gets the value of the minWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinWidth() {
        return minWidth;
    }

    /**
     * Sets the value of the minWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinWidth(BigDecimal value) {
        this.minWidth = value;
    }

    /**
     * Gets the value of the autoMaxHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoMaxHeight() {
        return autoMaxHeight;
    }

    /**
     * Sets the value of the autoMaxHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoMaxHeight(Boolean value) {
        this.autoMaxHeight = value;
    }

    /**
     * Gets the value of the maxHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxHeight() {
        return maxHeight;
    }

    /**
     * Sets the value of the maxHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxHeight(BigDecimal value) {
        this.maxHeight = value;
    }

    /**
     * Gets the value of the choiceMode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isChoiceMode() {
        return choiceMode;
    }

    /**
     * Sets the value of the choiceMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChoiceMode(Boolean value) {
        this.choiceMode = value;
    }

    /**
     * Gets the value of the multipleChoice property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMultipleChoice() {
        return multipleChoice;
    }

    /**
     * Sets the value of the multipleChoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultipleChoice(Boolean value) {
        this.multipleChoice = value;
    }

    /**
     * Gets the value of the rowInput property.
     * 
     * @return
     *     possible object is
     *     {@link TableRowInputMode }
     *     
     */
    public TableRowInputMode getRowInput() {
        return rowInput;
    }

    /**
     * Sets the value of the rowInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableRowInputMode }
     *     
     */
    public void setRowInput(TableRowInputMode value) {
        this.rowInput = value;
    }

    /**
     * Gets the value of the rowsSelection property.
     * 
     * @return
     *     possible object is
     *     {@link TableSelectionMode }
     *     
     */
    public TableSelectionMode getRowsSelection() {
        return rowsSelection;
    }

    /**
     * Sets the value of the rowsSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableSelectionMode }
     *     
     */
    public void setRowsSelection(TableSelectionMode value) {
        this.rowsSelection = value;
    }

    /**
     * Gets the value of the rowSelection property.
     * 
     * @return
     *     possible object is
     *     {@link TableRowSelectionMode }
     *     
     */
    public TableRowSelectionMode getRowSelection() {
        return rowSelection;
    }

    /**
     * Sets the value of the rowSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableRowSelectionMode }
     *     
     */
    public void setRowSelection(TableRowSelectionMode value) {
        this.rowSelection = value;
    }

    /**
     * Gets the value of the showHeader property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowHeader() {
        return showHeader;
    }

    /**
     * Sets the value of the showHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowHeader(Boolean value) {
        this.showHeader = value;
    }

    /**
     * Gets the value of the headerHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHeaderHeight() {
        return headerHeight;
    }

    /**
     * Sets the value of the headerHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHeaderHeight(BigDecimal value) {
        this.headerHeight = value;
    }

    /**
     * Gets the value of the showFooter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowFooter() {
        return showFooter;
    }

    /**
     * Sets the value of the showFooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowFooter(Boolean value) {
        this.showFooter = value;
    }

    /**
     * Gets the value of the footerHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFooterHeight() {
        return footerHeight;
    }

    /**
     * Sets the value of the footerHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFooterHeight(BigDecimal value) {
        this.footerHeight = value;
    }

    /**
     * Gets the value of the horScroll property.
     * 
     * @return
     *     possible object is
     *     {@link TableScrollBarUse }
     *     
     */
    public TableScrollBarUse getHorScroll() {
        return horScroll;
    }

    /**
     * Sets the value of the horScroll property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableScrollBarUse }
     *     
     */
    public void setHorScroll(TableScrollBarUse value) {
        this.horScroll = value;
    }

    /**
     * Gets the value of the verScroll property.
     * 
     * @return
     *     possible object is
     *     {@link TableScrollBarUse }
     *     
     */
    public TableScrollBarUse getVerScroll() {
        return verScroll;
    }

    /**
     * Sets the value of the verScroll property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableScrollBarUse }
     *     
     */
    public void setVerScroll(TableScrollBarUse value) {
        this.verScroll = value;
    }

    /**
     * Gets the value of the showHorLines property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowHorLines() {
        return showHorLines;
    }

    /**
     * Sets the value of the showHorLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowHorLines(Boolean value) {
        this.showHorLines = value;
    }

    /**
     * Gets the value of the showVerLines property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowVerLines() {
        return showVerLines;
    }

    /**
     * Sets the value of the showVerLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowVerLines(Boolean value) {
        this.showVerLines = value;
    }

    /**
     * Gets the value of the fixedLeft property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFixedLeft() {
        return fixedLeft;
    }

    /**
     * Sets the value of the fixedLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFixedLeft(BigDecimal value) {
        this.fixedLeft = value;
    }

    /**
     * Gets the value of the fixedRight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFixedRight() {
        return fixedRight;
    }

    /**
     * Sets the value of the fixedRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFixedRight(BigDecimal value) {
        this.fixedRight = value;
    }

    /**
     * Gets the value of the useAltRowColor property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseAltRowColor() {
        return useAltRowColor;
    }

    /**
     * Sets the value of the useAltRowColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseAltRowColor(Boolean value) {
        this.useAltRowColor = value;
    }

    /**
     * Gets the value of the autoInsert property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoInsert() {
        return autoInsert;
    }

    /**
     * Sets the value of the autoInsert property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoInsert(Boolean value) {
        this.autoInsert = value;
    }

    /**
     * Gets the value of the autoInsertNotcompleted property.
     * 
     * @return
     *     possible object is
     *     {@link BWAValue }
     *     
     */
    public BWAValue getAutoInsertNotcompleted() {
        return autoInsertNotcompleted;
    }

    /**
     * Sets the value of the autoInsertNotcompleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link BWAValue }
     *     
     */
    public void setAutoInsertNotcompleted(BWAValue value) {
        this.autoInsertNotcompleted = value;
    }

    /**
     * Gets the value of the autoMarkNotcompleted property.
     * 
     * @return
     *     possible object is
     *     {@link BWAValue }
     *     
     */
    public BWAValue getAutoMarkNotcompleted() {
        return autoMarkNotcompleted;
    }

    /**
     * Sets the value of the autoMarkNotcompleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link BWAValue }
     *     
     */
    public void setAutoMarkNotcompleted(BWAValue value) {
        this.autoMarkNotcompleted = value;
    }

    /**
     * Gets the value of the searchOnInput property.
     * 
     * @return
     *     possible object is
     *     {@link SearchOnInput }
     *     
     */
    public SearchOnInput getSearchOnInput() {
        return searchOnInput;
    }

    /**
     * Sets the value of the searchOnInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchOnInput }
     *     
     */
    public void setSearchOnInput(SearchOnInput value) {
        this.searchOnInput = value;
    }

    /**
     * Gets the value of the initListView property.
     * 
     * @return
     *     possible object is
     *     {@link TableInitialListView }
     *     
     */
    public TableInitialListView getInitListView() {
        return initListView;
    }

    /**
     * Sets the value of the initListView property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableInitialListView }
     *     
     */
    public void setInitListView(TableInitialListView value) {
        this.initListView = value;
    }

    /**
     * Gets the value of the initTreeView property.
     * 
     * @return
     *     possible object is
     *     {@link TableInitialTreeView }
     *     
     */
    public TableInitialTreeView getInitTreeView() {
        return initTreeView;
    }

    /**
     * Sets the value of the initTreeView property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableInitialTreeView }
     *     
     */
    public void setInitTreeView(TableInitialTreeView value) {
        this.initTreeView = value;
    }

    /**
     * Gets the value of the useOutput property.
     * 
     * @return
     *     possible object is
     *     {@link UseOutput }
     *     
     */
    public UseOutput getUseOutput() {
        return useOutput;
    }

    /**
     * Sets the value of the useOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UseOutput }
     *     
     */
    public void setUseOutput(UseOutput value) {
        this.useOutput = value;
    }

    /**
     * Gets the value of the horStretch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHorStretch() {
        return horStretch;
    }

    /**
     * Sets the value of the horStretch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHorStretch(Boolean value) {
        this.horStretch = value;
    }

    /**
     * Gets the value of the verStretch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVerStretch() {
        return verStretch;
    }

    /**
     * Sets the value of the verStretch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVerStretch(Boolean value) {
        this.verStretch = value;
    }

    /**
     * Gets the value of the startDrag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStartDrag() {
        return startDrag;
    }

    /**
     * Sets the value of the startDrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStartDrag(Boolean value) {
        this.startDrag = value;
    }

    /**
     * Gets the value of the drag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDrag() {
        return drag;
    }

    /**
     * Sets the value of the drag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDrag(Boolean value) {
        this.drag = value;
    }

    /**
     * Gets the value of the tooltipRepres property.
     * 
     * @return
     *     possible object is
     *     {@link TooltipRepresentation }
     *     
     */
    public TooltipRepresentation getTooltipRepres() {
        return tooltipRepres;
    }

    /**
     * Sets the value of the tooltipRepres property.
     * 
     * @param value
     *     allowed object is
     *     {@link TooltipRepresentation }
     *     
     */
    public void setTooltipRepres(TooltipRepresentation value) {
        this.tooltipRepres = value;
    }

    /**
     * Gets the value of the searchStringLocation property.
     * 
     * @return
     *     possible object is
     *     {@link SearchStringLocation }
     *     
     */
    public SearchStringLocation getSearchStringLocation() {
        return searchStringLocation;
    }

    /**
     * Sets the value of the searchStringLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchStringLocation }
     *     
     */
    public void setSearchStringLocation(SearchStringLocation value) {
        this.searchStringLocation = value;
    }

    /**
     * Gets the value of the viewStatusLocation property.
     * 
     * @return
     *     possible object is
     *     {@link ViewStatusLocation }
     *     
     */
    public ViewStatusLocation getViewStatusLocation() {
        return viewStatusLocation;
    }

    /**
     * Sets the value of the viewStatusLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewStatusLocation }
     *     
     */
    public void setViewStatusLocation(ViewStatusLocation value) {
        this.viewStatusLocation = value;
    }

    /**
     * Gets the value of the searchControlLocation property.
     * 
     * @return
     *     possible object is
     *     {@link SearchControlLocation }
     *     
     */
    public SearchControlLocation getSearchControlLocation() {
        return searchControlLocation;
    }

    /**
     * Sets the value of the searchControlLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchControlLocation }
     *     
     */
    public void setSearchControlLocation(SearchControlLocation value) {
        this.searchControlLocation = value;
    }

    /**
     * Gets the value of the groupHAlign property.
     * 
     * @return
     *     possible object is
     *     {@link ItemHorizontalAlignment }
     *     
     */
    public ItemHorizontalAlignment getGroupHAlign() {
        return groupHAlign;
    }

    /**
     * Sets the value of the groupHAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemHorizontalAlignment }
     *     
     */
    public void setGroupHAlign(ItemHorizontalAlignment value) {
        this.groupHAlign = value;
    }

    /**
     * Gets the value of the groupVAlign property.
     * 
     * @return
     *     possible object is
     *     {@link ItemVerticalAlignment }
     *     
     */
    public ItemVerticalAlignment getGroupVAlign() {
        return groupVAlign;
    }

    /**
     * Sets the value of the groupVAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemVerticalAlignment }
     *     
     */
    public void setGroupVAlign(ItemVerticalAlignment value) {
        this.groupVAlign = value;
    }

    /**
     * Gets the value of the clearEvents property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClearEvents() {
        return clearEvents;
    }

    /**
     * Sets the value of the clearEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClearEvents(Boolean value) {
        this.clearEvents = value;
    }

    /**
     * Gets the value of the refreshRequest property.
     * 
     * @return
     *     possible object is
     *     {@link RefreshRequestMethod }
     *     
     */
    public RefreshRequestMethod getRefreshRequest() {
        return refreshRequest;
    }

    /**
     * Sets the value of the refreshRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefreshRequestMethod }
     *     
     */
    public void setRefreshRequest(RefreshRequestMethod value) {
        this.refreshRequest = value;
    }

}
