//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package org.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TreeChanges complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TreeChanges"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="operations" type="{http://v8.1c.ru/8.2/uobjects}TreeOperations" minOccurs="0"/&gt;
 *         &lt;element name="items" type="{http://v8.1c.ru/8.2/uobjects}TreeItemChangesList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TreeChanges", namespace = "http://v8.1c.ru/8.2/uobjects", propOrder = {
    "operations",
    "items"
})
public class TreeChanges {

    protected TreeOperations operations;
    protected TreeItemChangesList items;

    /**
     * Gets the value of the operations property.
     * 
     * @return
     *     possible object is
     *     {@link TreeOperations }
     *     
     */
    public TreeOperations getOperations() {
        return operations;
    }

    /**
     * Sets the value of the operations property.
     * 
     * @param value
     *     allowed object is
     *     {@link TreeOperations }
     *     
     */
    public void setOperations(TreeOperations value) {
        this.operations = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link TreeItemChangesList }
     *     
     */
    public TreeItemChangesList getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link TreeItemChangesList }
     *     
     */
    public void setItems(TreeItemChangesList value) {
        this.items = value;
    }

}
