//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for AccountingRegisterProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountingRegisterProperties"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Synonym" type="{http://v8.1c.ru/8.1/data/core}LocalStringType"/&gt;
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ObjectBelonging" type="{http://v8.1c.ru/8.3/xcf/enums}ObjectBelonging"/&gt;
 *         &lt;element name="UseStandardCommands" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IncludeHelpInContents" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Help" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="ChartOfAccounts" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="Correspondence" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="PeriodAdjustmentLength" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="DefaultListForm" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="AuxiliaryListForm" type="{http://v8.1c.ru/8.3/xcf/readable}MDObjectRef"/&gt;
 *         &lt;element name="RecordSetModule" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="ManagerModule" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="StandardAttributes" type="{http://v8.1c.ru/8.3/xcf/readable}StandardAttributeDescriptions"/&gt;
 *         &lt;element name="DataLockControlMode" type="{http://v8.1c.ru/8.3/xcf/enums}DefaultDataLockControlMode"/&gt;
 *         &lt;element name="EnableTotalsSplitting" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="FullTextSearch" type="{http://v8.1c.ru/8.3/xcf/enums}FullTextSearchUsing"/&gt;
 *         &lt;element name="ListPresentation" type="{http://v8.1c.ru/8.1/data/core}LocalStringType"/&gt;
 *         &lt;element name="ExtendedListPresentation" type="{http://v8.1c.ru/8.1/data/core}LocalStringType"/&gt;
 *         &lt;element name="Explanation" type="{http://v8.1c.ru/8.1/data/core}LocalStringType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountingRegisterProperties", propOrder = {
    "name",
    "synonym",
    "comment",
    "objectBelonging",
    "useStandardCommands",
    "includeHelpInContents",
    "help",
    "chartOfAccounts",
    "correspondence",
    "periodAdjustmentLength",
    "defaultListForm",
    "auxiliaryListForm",
    "recordSetModule",
    "managerModule",
    "standardAttributes",
    "dataLockControlMode",
    "enableTotalsSplitting",
    "fullTextSearch",
    "listPresentation",
    "extendedListPresentation",
    "explanation"
})
public class AccountingRegisterProperties {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Synonym", required = true)
    protected LocalStringType synonym;
    @XmlElement(name = "Comment", required = true)
    protected String comment;
    @XmlElement(name = "ObjectBelonging", required = true)
    @XmlSchemaType(name = "string")
    protected ObjectBelonging objectBelonging;
    @XmlElement(name = "UseStandardCommands")
    protected boolean useStandardCommands;
    @XmlElement(name = "IncludeHelpInContents")
    protected boolean includeHelpInContents;
    @XmlElement(name = "Help", required = true)
    protected String help;
    @XmlElement(name = "ChartOfAccounts", required = true)
    protected String chartOfAccounts;
    @XmlElement(name = "Correspondence")
    protected boolean correspondence;
    @XmlElement(name = "PeriodAdjustmentLength", required = true)
    protected BigDecimal periodAdjustmentLength;
    @XmlElement(name = "DefaultListForm", required = true)
    protected String defaultListForm;
    @XmlElement(name = "AuxiliaryListForm", required = true)
    protected String auxiliaryListForm;
    @XmlElement(name = "RecordSetModule", required = true)
    protected String recordSetModule;
    @XmlElement(name = "ManagerModule", required = true)
    protected String managerModule;
    @XmlElement(name = "StandardAttributes", required = true)
    protected StandardAttributeDescriptions standardAttributes;
    @XmlElement(name = "DataLockControlMode", required = true)
    @XmlSchemaType(name = "string")
    protected DefaultDataLockControlMode dataLockControlMode;
    @XmlElement(name = "EnableTotalsSplitting")
    protected boolean enableTotalsSplitting;
    @XmlElement(name = "FullTextSearch", required = true)
    @XmlSchemaType(name = "string")
    protected FullTextSearchUsing fullTextSearch;
    @XmlElement(name = "ListPresentation", required = true)
    protected LocalStringType listPresentation;
    @XmlElement(name = "ExtendedListPresentation", required = true)
    protected LocalStringType extendedListPresentation;
    @XmlElement(name = "Explanation", required = true)
    protected LocalStringType explanation;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the synonym property.
     * 
     * @return
     *     possible object is
     *     {@link LocalStringType }
     *     
     */
    public LocalStringType getSynonym() {
        return synonym;
    }

    /**
     * Sets the value of the synonym property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalStringType }
     *     
     */
    public void setSynonym(LocalStringType value) {
        this.synonym = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the objectBelonging property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectBelonging }
     *     
     */
    public ObjectBelonging getObjectBelonging() {
        return objectBelonging;
    }

    /**
     * Sets the value of the objectBelonging property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectBelonging }
     *     
     */
    public void setObjectBelonging(ObjectBelonging value) {
        this.objectBelonging = value;
    }

    /**
     * Gets the value of the useStandardCommands property.
     * 
     */
    public boolean isUseStandardCommands() {
        return useStandardCommands;
    }

    /**
     * Sets the value of the useStandardCommands property.
     * 
     */
    public void setUseStandardCommands(boolean value) {
        this.useStandardCommands = value;
    }

    /**
     * Gets the value of the includeHelpInContents property.
     * 
     */
    public boolean isIncludeHelpInContents() {
        return includeHelpInContents;
    }

    /**
     * Sets the value of the includeHelpInContents property.
     * 
     */
    public void setIncludeHelpInContents(boolean value) {
        this.includeHelpInContents = value;
    }

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelp(String value) {
        this.help = value;
    }

    /**
     * Gets the value of the chartOfAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartOfAccounts() {
        return chartOfAccounts;
    }

    /**
     * Sets the value of the chartOfAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartOfAccounts(String value) {
        this.chartOfAccounts = value;
    }

    /**
     * Gets the value of the correspondence property.
     * 
     */
    public boolean isCorrespondence() {
        return correspondence;
    }

    /**
     * Sets the value of the correspondence property.
     * 
     */
    public void setCorrespondence(boolean value) {
        this.correspondence = value;
    }

    /**
     * Gets the value of the periodAdjustmentLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPeriodAdjustmentLength() {
        return periodAdjustmentLength;
    }

    /**
     * Sets the value of the periodAdjustmentLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPeriodAdjustmentLength(BigDecimal value) {
        this.periodAdjustmentLength = value;
    }

    /**
     * Gets the value of the defaultListForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultListForm() {
        return defaultListForm;
    }

    /**
     * Sets the value of the defaultListForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultListForm(String value) {
        this.defaultListForm = value;
    }

    /**
     * Gets the value of the auxiliaryListForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuxiliaryListForm() {
        return auxiliaryListForm;
    }

    /**
     * Sets the value of the auxiliaryListForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuxiliaryListForm(String value) {
        this.auxiliaryListForm = value;
    }

    /**
     * Gets the value of the recordSetModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordSetModule() {
        return recordSetModule;
    }

    /**
     * Sets the value of the recordSetModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordSetModule(String value) {
        this.recordSetModule = value;
    }

    /**
     * Gets the value of the managerModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagerModule() {
        return managerModule;
    }

    /**
     * Sets the value of the managerModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagerModule(String value) {
        this.managerModule = value;
    }

    /**
     * Gets the value of the standardAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link StandardAttributeDescriptions }
     *     
     */
    public StandardAttributeDescriptions getStandardAttributes() {
        return standardAttributes;
    }

    /**
     * Sets the value of the standardAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardAttributeDescriptions }
     *     
     */
    public void setStandardAttributes(StandardAttributeDescriptions value) {
        this.standardAttributes = value;
    }

    /**
     * Gets the value of the dataLockControlMode property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultDataLockControlMode }
     *     
     */
    public DefaultDataLockControlMode getDataLockControlMode() {
        return dataLockControlMode;
    }

    /**
     * Sets the value of the dataLockControlMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultDataLockControlMode }
     *     
     */
    public void setDataLockControlMode(DefaultDataLockControlMode value) {
        this.dataLockControlMode = value;
    }

    /**
     * Gets the value of the enableTotalsSplitting property.
     * 
     */
    public boolean isEnableTotalsSplitting() {
        return enableTotalsSplitting;
    }

    /**
     * Sets the value of the enableTotalsSplitting property.
     * 
     */
    public void setEnableTotalsSplitting(boolean value) {
        this.enableTotalsSplitting = value;
    }

    /**
     * Gets the value of the fullTextSearch property.
     * 
     * @return
     *     possible object is
     *     {@link FullTextSearchUsing }
     *     
     */
    public FullTextSearchUsing getFullTextSearch() {
        return fullTextSearch;
    }

    /**
     * Sets the value of the fullTextSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullTextSearchUsing }
     *     
     */
    public void setFullTextSearch(FullTextSearchUsing value) {
        this.fullTextSearch = value;
    }

    /**
     * Gets the value of the listPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link LocalStringType }
     *     
     */
    public LocalStringType getListPresentation() {
        return listPresentation;
    }

    /**
     * Sets the value of the listPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalStringType }
     *     
     */
    public void setListPresentation(LocalStringType value) {
        this.listPresentation = value;
    }

    /**
     * Gets the value of the extendedListPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link LocalStringType }
     *     
     */
    public LocalStringType getExtendedListPresentation() {
        return extendedListPresentation;
    }

    /**
     * Sets the value of the extendedListPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalStringType }
     *     
     */
    public void setExtendedListPresentation(LocalStringType value) {
        this.extendedListPresentation = value;
    }

    /**
     * Gets the value of the explanation property.
     * 
     * @return
     *     possible object is
     *     {@link LocalStringType }
     *     
     */
    public LocalStringType getExplanation() {
        return explanation;
    }

    /**
     * Sets the value of the explanation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalStringType }
     *     
     */
    public void setExplanation(LocalStringType value) {
        this.explanation = value;
    }

}
