//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for Area complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Area"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="type" type="{http://v8.1c.ru/8.2/data/spreadsheet}SpreadsheetDocumentCellAreaType"/&gt;
 *         &lt;element name="beginRow" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="endRow" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="beginColumn" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="endColumn" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="columnsID" type="{http://v8.1c.ru/8.1/data/core}UUID" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Area", namespace = "http://v8.1c.ru/8.2/data/spreadsheet", propOrder = {
    "type",
    "beginRow",
    "endRow",
    "beginColumn",
    "endColumn",
    "columnsID"
})
public class Area {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected SpreadsheetDocumentCellAreaType type;
    protected BigDecimal beginRow;
    protected BigDecimal endRow;
    protected BigDecimal beginColumn;
    protected BigDecimal endColumn;
    protected String columnsID;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SpreadsheetDocumentCellAreaType }
     *     
     */
    public SpreadsheetDocumentCellAreaType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpreadsheetDocumentCellAreaType }
     *     
     */
    public void setType(SpreadsheetDocumentCellAreaType value) {
        this.type = value;
    }

    /**
     * Gets the value of the beginRow property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBeginRow() {
        return beginRow;
    }

    /**
     * Sets the value of the beginRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBeginRow(BigDecimal value) {
        this.beginRow = value;
    }

    /**
     * Gets the value of the endRow property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEndRow() {
        return endRow;
    }

    /**
     * Sets the value of the endRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEndRow(BigDecimal value) {
        this.endRow = value;
    }

    /**
     * Gets the value of the beginColumn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBeginColumn() {
        return beginColumn;
    }

    /**
     * Sets the value of the beginColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBeginColumn(BigDecimal value) {
        this.beginColumn = value;
    }

    /**
     * Gets the value of the endColumn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEndColumn() {
        return endColumn;
    }

    /**
     * Sets the value of the endColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEndColumn(BigDecimal value) {
        this.endColumn = value;
    }

    /**
     * Gets the value of the columnsID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnsID() {
        return columnsID;
    }

    /**
     * Sets the value of the columnsID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnsID(String value) {
        this.columnsID = value;
    }

}
