//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClientCMIUpdateInterfaceDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClientCMIUpdateInterfaceDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="foVer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="defaultNP" type="{http://v8.1c.ru/8.2/managed-application/core}NavigationPoint" minOccurs="0"/&gt;
 *         &lt;element name="currentNPUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="startUpData" type="{http://v8.1c.ru/8.2/managed-application/cmi}ClientCMIStartUpDataType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClientCMIUpdateInterfaceDataType", namespace = "http://v8.1c.ru/8.2/managed-application/cmi", propOrder = {
    "foVer",
    "defaultNP",
    "currentNPUrl",
    "startUpData"
})
public class ClientCMIUpdateInterfaceDataType {

    protected String foVer;
    protected NavigationPoint defaultNP;
    protected String currentNPUrl;
    protected ClientCMIStartUpDataType startUpData;

    /**
     * Gets the value of the foVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoVer() {
        return foVer;
    }

    /**
     * Sets the value of the foVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoVer(String value) {
        this.foVer = value;
    }

    /**
     * Gets the value of the defaultNP property.
     * 
     * @return
     *     possible object is
     *     {@link NavigationPoint }
     *     
     */
    public NavigationPoint getDefaultNP() {
        return defaultNP;
    }

    /**
     * Sets the value of the defaultNP property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavigationPoint }
     *     
     */
    public void setDefaultNP(NavigationPoint value) {
        this.defaultNP = value;
    }

    /**
     * Gets the value of the currentNPUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentNPUrl() {
        return currentNPUrl;
    }

    /**
     * Sets the value of the currentNPUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentNPUrl(String value) {
        this.currentNPUrl = value;
    }

    /**
     * Gets the value of the startUpData property.
     * 
     * @return
     *     possible object is
     *     {@link ClientCMIStartUpDataType }
     *     
     */
    public ClientCMIStartUpDataType getStartUpData() {
        return startUpData;
    }

    /**
     * Sets the value of the startUpData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientCMIStartUpDataType }
     *     
     */
    public void setStartUpData(ClientCMIStartUpDataType value) {
        this.startUpData = value;
    }

}
