//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for CommandInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommandInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tooltip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pic" type="{http://v8.1c.ru/8.1/data/ui}Picture" minOccurs="0"/&gt;
 *         &lt;element name="picSizeCX" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="picSizeCY" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="shortcut" type="{http://v8.1c.ru/8.1/data/ui}ShortCutType" minOccurs="0"/&gt;
 *         &lt;element name="param" type="{http://v8.1c.ru/8.1/data/core}TypeDescription" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" use="required" type="{http://v8.1c.ru/8.1/data/core}CompositeID" /&gt;
 *       &lt;attribute name="nameInt" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="nameRus" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="md" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="kind" type="{http://v8.1c.ru/8.2/managed-application/logform}ButtonRepresentation" /&gt;
 *       &lt;attribute name="helpTopic" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommandInfo", namespace = "http://v8.1c.ru/8.2/managed-application/cmi", propOrder = {
    "text",
    "tooltip",
    "pic",
    "picSizeCX",
    "picSizeCY",
    "shortcut",
    "param"
})
@XmlSeeAlso({
    CommandCMI.class
})
public class CommandInfo {

    protected String text;
    protected String tooltip;
    protected Picture pic;
    protected BigDecimal picSizeCX;
    protected BigDecimal picSizeCY;
    protected ShortCutType shortcut;
    protected TypeDescription param;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "nameInt", required = true)
    protected String nameInt;
    @XmlAttribute(name = "nameRus", required = true)
    protected String nameRus;
    @XmlAttribute(name = "md", required = true)
    protected String md;
    @XmlAttribute(name = "kind")
    protected ButtonRepresentation kind;
    @XmlAttribute(name = "helpTopic", required = true)
    protected String helpTopic;
    @XmlAttribute(name = "url", required = true)
    protected String url;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the tooltip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTooltip() {
        return tooltip;
    }

    /**
     * Sets the value of the tooltip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTooltip(String value) {
        this.tooltip = value;
    }

    /**
     * Gets the value of the pic property.
     * 
     * @return
     *     possible object is
     *     {@link Picture }
     *     
     */
    public Picture getPic() {
        return pic;
    }

    /**
     * Sets the value of the pic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Picture }
     *     
     */
    public void setPic(Picture value) {
        this.pic = value;
    }

    /**
     * Gets the value of the picSizeCX property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPicSizeCX() {
        return picSizeCX;
    }

    /**
     * Sets the value of the picSizeCX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPicSizeCX(BigDecimal value) {
        this.picSizeCX = value;
    }

    /**
     * Gets the value of the picSizeCY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPicSizeCY() {
        return picSizeCY;
    }

    /**
     * Sets the value of the picSizeCY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPicSizeCY(BigDecimal value) {
        this.picSizeCY = value;
    }

    /**
     * Gets the value of the shortcut property.
     * 
     * @return
     *     possible object is
     *     {@link ShortCutType }
     *     
     */
    public ShortCutType getShortcut() {
        return shortcut;
    }

    /**
     * Sets the value of the shortcut property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShortCutType }
     *     
     */
    public void setShortcut(ShortCutType value) {
        this.shortcut = value;
    }

    /**
     * Gets the value of the param property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDescription }
     *     
     */
    public TypeDescription getParam() {
        return param;
    }

    /**
     * Sets the value of the param property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDescription }
     *     
     */
    public void setParam(TypeDescription value) {
        this.param = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the nameInt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameInt() {
        return nameInt;
    }

    /**
     * Sets the value of the nameInt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameInt(String value) {
        this.nameInt = value;
    }

    /**
     * Gets the value of the nameRus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameRus() {
        return nameRus;
    }

    /**
     * Sets the value of the nameRus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameRus(String value) {
        this.nameRus = value;
    }

    /**
     * Gets the value of the md property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMd() {
        return md;
    }

    /**
     * Sets the value of the md property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMd(String value) {
        this.md = value;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link ButtonRepresentation }
     *     
     */
    public ButtonRepresentation getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link ButtonRepresentation }
     *     
     */
    public void setKind(ButtonRepresentation value) {
        this.kind = value;
    }

    /**
     * Gets the value of the helpTopic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelpTopic() {
        return helpTopic;
    }

    /**
     * Sets the value of the helpTopic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelpTopic(String value) {
        this.helpTopic = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

}
