//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for CommonModuleProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommonModuleProperties"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Synonym" type="{http://v8.1c.ru/8.1/data/core}LocalStringType"/&gt;
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ObjectBelonging" type="{http://v8.1c.ru/8.3/xcf/enums}ObjectBelonging"/&gt;
 *         &lt;element name="Module" type="{http://v8.1c.ru/8.3/xcf/readable}ExternalProperty"/&gt;
 *         &lt;element name="Global" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ClientManagedApplication" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Server" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ExternalConnection" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ClientOrdinaryApplication" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Client" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ServerCall" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Privileged" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ReturnValuesReuse" type="{http://v8.1c.ru/8.3/xcf/enums}ReturnValuesReuse"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommonModuleProperties", propOrder = {
    "name",
    "synonym",
    "comment",
    "objectBelonging",
    "module",
    "global",
    "clientManagedApplication",
    "server",
    "externalConnection",
    "clientOrdinaryApplication",
    "client",
    "serverCall",
    "privileged",
    "returnValuesReuse"
})
public class CommonModuleProperties {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Synonym")
    protected LocalStringType synonym;
    @XmlElement(name = "Comment")
    protected String comment;
    @XmlElement(name = "ObjectBelonging")
    @XmlSchemaType(name = "string")
    protected ObjectBelonging objectBelonging;
    @XmlElement(name = "Module")
    protected String module;
    @XmlElement(name = "Global")
    protected Boolean global;
    @XmlElement(name = "ClientManagedApplication")
    protected Boolean clientManagedApplication;
    @XmlElement(name = "Server")
    protected Boolean server;
    @XmlElement(name = "ExternalConnection")
    protected Boolean externalConnection;
    @XmlElement(name = "ClientOrdinaryApplication")
    protected Boolean clientOrdinaryApplication;
    @XmlElement(name = "Client")
    protected Boolean client;
    @XmlElement(name = "ServerCall")
    protected Boolean serverCall;
    @XmlElement(name = "Privileged")
    protected Boolean privileged;
    @XmlElement(name = "ReturnValuesReuse")
    @XmlSchemaType(name = "string")
    protected ReturnValuesReuse returnValuesReuse;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the synonym property.
     * 
     * @return
     *     possible object is
     *     {@link LocalStringType }
     *     
     */
    public LocalStringType getSynonym() {
        return synonym;
    }

    /**
     * Sets the value of the synonym property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalStringType }
     *     
     */
    public void setSynonym(LocalStringType value) {
        this.synonym = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the objectBelonging property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectBelonging }
     *     
     */
    public ObjectBelonging getObjectBelonging() {
        return objectBelonging;
    }

    /**
     * Sets the value of the objectBelonging property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectBelonging }
     *     
     */
    public void setObjectBelonging(ObjectBelonging value) {
        this.objectBelonging = value;
    }

    /**
     * Gets the value of the module property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModule() {
        return module;
    }

    /**
     * Sets the value of the module property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModule(String value) {
        this.module = value;
    }

    /**
     * Gets the value of the global property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGlobal() {
        return global;
    }

    /**
     * Sets the value of the global property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGlobal(Boolean value) {
        this.global = value;
    }

    /**
     * Gets the value of the clientManagedApplication property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClientManagedApplication() {
        return clientManagedApplication;
    }

    /**
     * Sets the value of the clientManagedApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClientManagedApplication(Boolean value) {
        this.clientManagedApplication = value;
    }

    /**
     * Gets the value of the server property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isServer() {
        return server;
    }

    /**
     * Sets the value of the server property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setServer(Boolean value) {
        this.server = value;
    }

    /**
     * Gets the value of the externalConnection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExternalConnection() {
        return externalConnection;
    }

    /**
     * Sets the value of the externalConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExternalConnection(Boolean value) {
        this.externalConnection = value;
    }

    /**
     * Gets the value of the clientOrdinaryApplication property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClientOrdinaryApplication() {
        return clientOrdinaryApplication;
    }

    /**
     * Sets the value of the clientOrdinaryApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClientOrdinaryApplication(Boolean value) {
        this.clientOrdinaryApplication = value;
    }

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClient(Boolean value) {
        this.client = value;
    }

    /**
     * Gets the value of the serverCall property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isServerCall() {
        return serverCall;
    }

    /**
     * Sets the value of the serverCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setServerCall(Boolean value) {
        this.serverCall = value;
    }

    /**
     * Gets the value of the privileged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrivileged() {
        return privileged;
    }

    /**
     * Sets the value of the privileged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrivileged(Boolean value) {
        this.privileged = value;
    }

    /**
     * Gets the value of the returnValuesReuse property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnValuesReuse }
     *     
     */
    public ReturnValuesReuse getReturnValuesReuse() {
        return returnValuesReuse;
    }

    /**
     * Sets the value of the returnValuesReuse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnValuesReuse }
     *     
     */
    public void setReturnValuesReuse(ReturnValuesReuse value) {
        this.returnValuesReuse = value;
    }

}
