//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.*;
import javax.xml.namespace.QName;


/**
 * <p>Java class for InfoRegKey complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfoRegKey"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://v8.1c.ru/8.2/managed-application/core}Type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dim" type="{http://v8.1c.ru/8.2/managed-application/core}InfoRegKeyDim"/&gt;
 *         &lt;element name="sep" type="{http://v8.1c.ru/8.2/managed-application/core}InfoRegKeyDim"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="recorder" type="{http://www.w3.org/2001/XMLSchema}QName" /&gt;
 *       &lt;attribute name="period" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="present" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="timePeriodicity" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoRegKey", namespace = "http://v8.1c.ru/8.2/managed-application/core", propOrder = {
    "dim",
    "sep"
})
public class InfoRegKey
    extends Type
{

    @XmlElement(required = true)
    protected InfoRegKeyDim dim;
    @XmlElement(required = true)
    protected InfoRegKeyDim sep;
    @XmlAttribute(name = "recorder")
    protected QName recorder;
    @XmlAttribute(name = "period")
    protected Boolean period;
    @XmlAttribute(name = "present")
    protected String present;
    @XmlAttribute(name = "timePeriodicity")
    protected Boolean timePeriodicity;

    /**
     * Gets the value of the dim property.
     * 
     * @return
     *     possible object is
     *     {@link InfoRegKeyDim }
     *     
     */
    public InfoRegKeyDim getDim() {
        return dim;
    }

    /**
     * Sets the value of the dim property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoRegKeyDim }
     *     
     */
    public void setDim(InfoRegKeyDim value) {
        this.dim = value;
    }

    /**
     * Gets the value of the sep property.
     * 
     * @return
     *     possible object is
     *     {@link InfoRegKeyDim }
     *     
     */
    public InfoRegKeyDim getSep() {
        return sep;
    }

    /**
     * Sets the value of the sep property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoRegKeyDim }
     *     
     */
    public void setSep(InfoRegKeyDim value) {
        this.sep = value;
    }

    /**
     * Gets the value of the recorder property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getRecorder() {
        return recorder;
    }

    /**
     * Sets the value of the recorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setRecorder(QName value) {
        this.recorder = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPeriod(Boolean value) {
        this.period = value;
    }

    /**
     * Gets the value of the present property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresent() {
        return present;
    }

    /**
     * Sets the value of the present property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresent(String value) {
        this.present = value;
    }

    /**
     * Gets the value of the timePeriodicity property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTimePeriodicity() {
        return timePeriodicity;
    }

    /**
     * Sets the value of the timePeriodicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTimePeriodicity(Boolean value) {
        this.timePeriodicity = value;
    }

}
