//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 09:46:06 PM KRAT 
//


package com.github._1c_syntax.mdclasses.jabx.original;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Predefined complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Predefined"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="contextMenu" type="{http://v8.1c.ru/8.2/managed-application/logform}GroupLogForm" minOccurs="0"/&gt;
 *         &lt;element name="contextMenuRef" type="{http://v8.1c.ru/8.2/managed-application/logform}ItemRef" minOccurs="0"/&gt;
 *         &lt;element name="autoCommandBar" type="{http://v8.1c.ru/8.2/managed-application/logform}GroupLogForm" minOccurs="0"/&gt;
 *         &lt;element name="autoCommandBarRef" type="{http://v8.1c.ru/8.2/managed-application/logform}ItemRef" minOccurs="0"/&gt;
 *         &lt;element name="extTooltip" type="{http://v8.1c.ru/8.2/managed-application/logform}Decoration" minOccurs="0"/&gt;
 *         &lt;element name="extTooltipRef" type="{http://v8.1c.ru/8.2/managed-application/logform}ItemRef" minOccurs="0"/&gt;
 *         &lt;element name="searchStringRepresentation" type="{http://v8.1c.ru/8.2/managed-application/logform}Addition" minOccurs="0"/&gt;
 *         &lt;element name="searchStringRepresentationRef" type="{http://v8.1c.ru/8.2/managed-application/logform}ItemRef" minOccurs="0"/&gt;
 *         &lt;element name="viewStatusRepresentation" type="{http://v8.1c.ru/8.2/managed-application/logform}Addition" minOccurs="0"/&gt;
 *         &lt;element name="viewStatusRepresentationRef" type="{http://v8.1c.ru/8.2/managed-application/logform}ItemRef" minOccurs="0"/&gt;
 *         &lt;element name="searchControl" type="{http://v8.1c.ru/8.2/managed-application/logform}Addition" minOccurs="0"/&gt;
 *         &lt;element name="searchControlRef" type="{http://v8.1c.ru/8.2/managed-application/logform}ItemRef" minOccurs="0"/&gt;
 *         &lt;element name="predefined" type="{http://v8.1c.ru/8.2/managed-application/logform}Predefined" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="field" type="{http://v8.1c.ru/8.2/managed-application/logform}FieldLogForm" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="group" type="{http://v8.1c.ru/8.2/managed-application/logform}GroupLogForm" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="table" type="{http://v8.1c.ru/8.2/managed-application/logform}TableLogForm" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="button" type="{http://v8.1c.ru/8.2/managed-application/logform}Button" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="decoration" type="{http://v8.1c.ru/8.2/managed-application/logform}Decoration" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="addition" type="{http://v8.1c.ru/8.2/managed-application/logform}Addition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Predefined", namespace = "http://v8.1c.ru/8.2/managed-application/logform", propOrder = {
    "contextMenu",
    "contextMenuRef",
    "autoCommandBar",
    "autoCommandBarRef",
    "extTooltip",
    "extTooltipRef",
    "searchStringRepresentation",
    "searchStringRepresentationRef",
    "viewStatusRepresentation",
    "viewStatusRepresentationRef",
    "searchControl",
    "searchControlRef",
    "predefined",
    "field",
    "group",
    "table",
    "button",
    "decoration",
    "addition"
})
public class Predefined {

    protected GroupLogForm contextMenu;
    protected ItemRef contextMenuRef;
    protected GroupLogForm autoCommandBar;
    protected ItemRef autoCommandBarRef;
    protected Decoration extTooltip;
    protected ItemRef extTooltipRef;
    protected Addition searchStringRepresentation;
    protected ItemRef searchStringRepresentationRef;
    protected Addition viewStatusRepresentation;
    protected ItemRef viewStatusRepresentationRef;
    protected Addition searchControl;
    protected ItemRef searchControlRef;
    protected List<Predefined> predefined;
    protected List<FieldLogForm> field;
    protected List<GroupLogForm> group;
    protected List<TableLogForm> table;
    protected List<Button> button;
    protected List<Decoration> decoration;
    protected List<Addition> addition;

    /**
     * Gets the value of the contextMenu property.
     * 
     * @return
     *     possible object is
     *     {@link GroupLogForm }
     *     
     */
    public GroupLogForm getContextMenu() {
        return contextMenu;
    }

    /**
     * Sets the value of the contextMenu property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupLogForm }
     *     
     */
    public void setContextMenu(GroupLogForm value) {
        this.contextMenu = value;
    }

    /**
     * Gets the value of the contextMenuRef property.
     * 
     * @return
     *     possible object is
     *     {@link ItemRef }
     *     
     */
    public ItemRef getContextMenuRef() {
        return contextMenuRef;
    }

    /**
     * Sets the value of the contextMenuRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemRef }
     *     
     */
    public void setContextMenuRef(ItemRef value) {
        this.contextMenuRef = value;
    }

    /**
     * Gets the value of the autoCommandBar property.
     * 
     * @return
     *     possible object is
     *     {@link GroupLogForm }
     *     
     */
    public GroupLogForm getAutoCommandBar() {
        return autoCommandBar;
    }

    /**
     * Sets the value of the autoCommandBar property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupLogForm }
     *     
     */
    public void setAutoCommandBar(GroupLogForm value) {
        this.autoCommandBar = value;
    }

    /**
     * Gets the value of the autoCommandBarRef property.
     * 
     * @return
     *     possible object is
     *     {@link ItemRef }
     *     
     */
    public ItemRef getAutoCommandBarRef() {
        return autoCommandBarRef;
    }

    /**
     * Sets the value of the autoCommandBarRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemRef }
     *     
     */
    public void setAutoCommandBarRef(ItemRef value) {
        this.autoCommandBarRef = value;
    }

    /**
     * Gets the value of the extTooltip property.
     * 
     * @return
     *     possible object is
     *     {@link Decoration }
     *     
     */
    public Decoration getExtTooltip() {
        return extTooltip;
    }

    /**
     * Sets the value of the extTooltip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Decoration }
     *     
     */
    public void setExtTooltip(Decoration value) {
        this.extTooltip = value;
    }

    /**
     * Gets the value of the extTooltipRef property.
     * 
     * @return
     *     possible object is
     *     {@link ItemRef }
     *     
     */
    public ItemRef getExtTooltipRef() {
        return extTooltipRef;
    }

    /**
     * Sets the value of the extTooltipRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemRef }
     *     
     */
    public void setExtTooltipRef(ItemRef value) {
        this.extTooltipRef = value;
    }

    /**
     * Gets the value of the searchStringRepresentation property.
     * 
     * @return
     *     possible object is
     *     {@link Addition }
     *     
     */
    public Addition getSearchStringRepresentation() {
        return searchStringRepresentation;
    }

    /**
     * Sets the value of the searchStringRepresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addition }
     *     
     */
    public void setSearchStringRepresentation(Addition value) {
        this.searchStringRepresentation = value;
    }

    /**
     * Gets the value of the searchStringRepresentationRef property.
     * 
     * @return
     *     possible object is
     *     {@link ItemRef }
     *     
     */
    public ItemRef getSearchStringRepresentationRef() {
        return searchStringRepresentationRef;
    }

    /**
     * Sets the value of the searchStringRepresentationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemRef }
     *     
     */
    public void setSearchStringRepresentationRef(ItemRef value) {
        this.searchStringRepresentationRef = value;
    }

    /**
     * Gets the value of the viewStatusRepresentation property.
     * 
     * @return
     *     possible object is
     *     {@link Addition }
     *     
     */
    public Addition getViewStatusRepresentation() {
        return viewStatusRepresentation;
    }

    /**
     * Sets the value of the viewStatusRepresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addition }
     *     
     */
    public void setViewStatusRepresentation(Addition value) {
        this.viewStatusRepresentation = value;
    }

    /**
     * Gets the value of the viewStatusRepresentationRef property.
     * 
     * @return
     *     possible object is
     *     {@link ItemRef }
     *     
     */
    public ItemRef getViewStatusRepresentationRef() {
        return viewStatusRepresentationRef;
    }

    /**
     * Sets the value of the viewStatusRepresentationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemRef }
     *     
     */
    public void setViewStatusRepresentationRef(ItemRef value) {
        this.viewStatusRepresentationRef = value;
    }

    /**
     * Gets the value of the searchControl property.
     * 
     * @return
     *     possible object is
     *     {@link Addition }
     *     
     */
    public Addition getSearchControl() {
        return searchControl;
    }

    /**
     * Sets the value of the searchControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addition }
     *     
     */
    public void setSearchControl(Addition value) {
        this.searchControl = value;
    }

    /**
     * Gets the value of the searchControlRef property.
     * 
     * @return
     *     possible object is
     *     {@link ItemRef }
     *     
     */
    public ItemRef getSearchControlRef() {
        return searchControlRef;
    }

    /**
     * Sets the value of the searchControlRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemRef }
     *     
     */
    public void setSearchControlRef(ItemRef value) {
        this.searchControlRef = value;
    }

    /**
     * Gets the value of the predefined property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the predefined property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPredefined().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Predefined }
     * 
     * 
     */
    public List<Predefined> getPredefined() {
        if (predefined == null) {
            predefined = new ArrayList<Predefined>();
        }
        return this.predefined;
    }

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldLogForm }
     * 
     * 
     */
    public List<FieldLogForm> getField() {
        if (field == null) {
            field = new ArrayList<FieldLogForm>();
        }
        return this.field;
    }

    /**
     * Gets the value of the group property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the group property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupLogForm }
     * 
     * 
     */
    public List<GroupLogForm> getGroup() {
        if (group == null) {
            group = new ArrayList<GroupLogForm>();
        }
        return this.group;
    }

    /**
     * Gets the value of the table property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the table property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TableLogForm }
     * 
     * 
     */
    public List<TableLogForm> getTable() {
        if (table == null) {
            table = new ArrayList<TableLogForm>();
        }
        return this.table;
    }

    /**
     * Gets the value of the button property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the button property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getButton().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Button }
     * 
     * 
     */
    public List<Button> getButton() {
        if (button == null) {
            button = new ArrayList<Button>();
        }
        return this.button;
    }

    /**
     * Gets the value of the decoration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the decoration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDecoration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Decoration }
     * 
     * 
     */
    public List<Decoration> getDecoration() {
        if (decoration == null) {
            decoration = new ArrayList<Decoration>();
        }
        return this.decoration;
    }

    /**
     * Gets the value of the addition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Addition }
     * 
     * 
     */
    public List<Addition> getAddition() {
        if (addition == null) {
            addition = new ArrayList<Addition>();
        }
        return this.addition;
    }

}
