name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: ['17', '21', '23']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: windows-latest
            prefix: win
          - os: ubuntu-latest
            prefix: nix
          - os: macOS-latest
            prefix: mac
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true
        lfs: true
        fetch-depth: 0
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'liberica'
    - name: Build with Gradle
      run: ./gradlew check --stacktrace
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
          name: Test Results (Java ${{ matrix.java_version }}.${{ matrix.os }})
          path: "**/test-results/test/**/*.xml"
  publish-test-results:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: "artifacts/**/*.xml"
