name: QA

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  QA:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.event.repository.full_name
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: ''
          submodules: true
          lfs: true
      - run: |
          git fetch --prune --unshallow
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'liberica'
      - name: SonarCloud Scan
        run: ./gradlew check sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}